// Mocks generated by Mockito 5.4.6 from annotations
// in auravibes_app/test/domain/usecases/tools/execution/check_tool_permission_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:auravibes_app/domain/entities/conversation_tool.dart' as _i5;
import 'package:auravibes_app/domain/entities/tools_group.dart' as _i8;
import 'package:auravibes_app/domain/entities/workspace_tool.dart' as _i2;
import 'package:auravibes_app/domain/enums/tool_permission_result.dart' as _i6;
import 'package:auravibes_app/domain/repositories/conversation_tools_repository.dart'
    as _i3;
import 'package:auravibes_app/domain/repositories/tools_groups_repository.dart'
    as _i7;
import 'package:auravibes_app/domain/repositories/workspace_tools_repository.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWorkspaceToolEntity_0 extends _i1.SmartFake
    implements _i2.WorkspaceToolEntity {
  _FakeWorkspaceToolEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ConversationToolsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationToolsRepository extends _i1.Mock
    implements _i3.ConversationToolsRepository {
  MockConversationToolsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.ConversationToolEntity>> getConversationTools(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationTools, [conversationId]),
            returnValue: _i4.Future<List<_i5.ConversationToolEntity>>.value(
              <_i5.ConversationToolEntity>[],
            ),
          )
          as _i4.Future<List<_i5.ConversationToolEntity>>);

  @override
  _i4.Future<List<_i5.ConversationToolEntity>> getEnabledConversationTools(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEnabledConversationTools, [conversationId]),
            returnValue: _i4.Future<List<_i5.ConversationToolEntity>>.value(
              <_i5.ConversationToolEntity>[],
            ),
          )
          as _i4.Future<List<_i5.ConversationToolEntity>>);

  @override
  _i4.Future<_i5.ConversationToolEntity?> getConversationTool(
    String? conversationId,
    String? toolId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationTool, [conversationId, toolId]),
            returnValue: _i4.Future<_i5.ConversationToolEntity?>.value(),
          )
          as _i4.Future<_i5.ConversationToolEntity?>);

  @override
  _i4.Future<bool> setConversationToolEnabled(
    String? conversationId,
    String? toolId, {
    required bool? isEnabled,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setConversationToolEnabled,
              [conversationId, toolId],
              {#isEnabled: isEnabled},
            ),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> setConversationToolsDisabled(
    String? conversationId,
    List<String>? toolIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setConversationToolsDisabled, [
              conversationId,
              toolIds,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> setConversationToolPermission(
    String? conversationId,
    String? toolId, {
    required _i2.ToolPermissionMode? permissionMode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setConversationToolPermission,
              [conversationId, toolId],
              {#permissionMode: permissionMode},
            ),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> toggleConversationTool(
    String? conversationId,
    String? toolId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleConversationTool, [
              conversationId,
              toolId,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> isConversationToolEnabled(
    String? conversationId,
    String? toolId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isConversationToolEnabled, [
              conversationId,
              toolId,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> removeConversationTool(
    String? conversationId,
    String? toolId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeConversationTool, [
              conversationId,
              toolId,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<int> getConversationToolsCount(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationToolsCount, [conversationId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> getEnabledConversationToolsCount(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getEnabledConversationToolsCount, [
              conversationId,
            ]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> copyConversationTools(
    String? sourceConversationId,
    String? targetConversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#copyConversationTools, [
              sourceConversationId,
              targetConversationId,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> validateConversationToolSetting(
    String? conversationId,
    String? toolId, {
    required bool? isEnabled,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #validateConversationToolSetting,
              [conversationId, toolId],
              {#isEnabled: isEnabled},
            ),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> isToolAvailableForConversation(
    String? conversationId,
    String? workspaceId,
    String? toolId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isToolAvailableForConversation, [
              conversationId,
              workspaceId,
              toolId,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<String>> getAvailableToolsForConversation(
    String? conversationId,
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableToolsForConversation, [
              conversationId,
              workspaceId,
            ]),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<List<_i2.WorkspaceToolEntity>>
  getAvailableToolEntitiesForConversation(
    String? conversationId,
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableToolEntitiesForConversation, [
              conversationId,
              workspaceId,
            ]),
            returnValue: _i4.Future<List<_i2.WorkspaceToolEntity>>.value(
              <_i2.WorkspaceToolEntity>[],
            ),
          )
          as _i4.Future<List<_i2.WorkspaceToolEntity>>);

  @override
  _i4.Future<_i6.ToolPermissionResult> checkToolPermission({
    required String? conversationId,
    required String? workspaceId,
    required String? toolId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#checkToolPermission, [], {
              #conversationId: conversationId,
              #workspaceId: workspaceId,
              #toolId: toolId,
            }),
            returnValue: _i4.Future<_i6.ToolPermissionResult>.value(
              _i6.ToolPermissionResult.granted,
            ),
          )
          as _i4.Future<_i6.ToolPermissionResult>);
}

/// A class which mocks [ToolsGroupsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockToolsGroupsRepository extends _i1.Mock
    implements _i7.ToolsGroupsRepository {
  MockToolsGroupsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i8.ToolsGroupEntity>> getToolsGroupsForWorkspace(
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getToolsGroupsForWorkspace, [workspaceId]),
            returnValue: _i4.Future<List<_i8.ToolsGroupEntity>>.value(
              <_i8.ToolsGroupEntity>[],
            ),
          )
          as _i4.Future<List<_i8.ToolsGroupEntity>>);

  @override
  _i4.Future<_i8.ToolsGroupEntity?> getToolsGroupById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getToolsGroupById, [id]),
            returnValue: _i4.Future<_i8.ToolsGroupEntity?>.value(),
          )
          as _i4.Future<_i8.ToolsGroupEntity?>);

  @override
  _i4.Future<_i8.ToolsGroupEntity?> getToolsGroupByMcpServerId(
    String? mcpServerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getToolsGroupByMcpServerId, [mcpServerId]),
            returnValue: _i4.Future<_i8.ToolsGroupEntity?>.value(),
          )
          as _i4.Future<_i8.ToolsGroupEntity?>);

  @override
  _i4.Future<bool> setToolsGroupEnabled(
    String? groupId, {
    required bool? isEnabled,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setToolsGroupEnabled,
              [groupId],
              {#isEnabled: isEnabled},
            ),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteToolsGroup(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteToolsGroup, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [WorkspaceToolsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkspaceToolsRepository extends _i1.Mock
    implements _i9.WorkspaceToolsRepository {
  MockWorkspaceToolsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.WorkspaceToolEntity>> getWorkspaceTools(
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkspaceTools, [workspaceId]),
            returnValue: _i4.Future<List<_i2.WorkspaceToolEntity>>.value(
              <_i2.WorkspaceToolEntity>[],
            ),
          )
          as _i4.Future<List<_i2.WorkspaceToolEntity>>);

  @override
  _i4.Future<List<_i2.WorkspaceToolEntity>> getEnabledWorkspaceTools(
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEnabledWorkspaceTools, [workspaceId]),
            returnValue: _i4.Future<List<_i2.WorkspaceToolEntity>>.value(
              <_i2.WorkspaceToolEntity>[],
            ),
          )
          as _i4.Future<List<_i2.WorkspaceToolEntity>>);

  @override
  _i4.Future<_i2.WorkspaceToolEntity?> getWorkspaceTool(
    String? workspaceId,
    String? toolType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkspaceTool, [workspaceId, toolType]),
            returnValue: _i4.Future<_i2.WorkspaceToolEntity?>.value(),
          )
          as _i4.Future<_i2.WorkspaceToolEntity?>);

  @override
  _i4.Future<_i2.WorkspaceToolEntity> setWorkspaceToolEnabled(
    String? workspaceId,
    String? toolType, {
    required bool? isEnabled,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setWorkspaceToolEnabled,
              [workspaceId, toolType],
              {#isEnabled: isEnabled},
            ),
            returnValue: _i4.Future<_i2.WorkspaceToolEntity>.value(
              _FakeWorkspaceToolEntity_0(
                this,
                Invocation.method(
                  #setWorkspaceToolEnabled,
                  [workspaceId, toolType],
                  {#isEnabled: isEnabled},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.WorkspaceToolEntity>);

  @override
  _i4.Future<_i2.WorkspaceToolEntity?> getWorkspaceToolByToolName({
    required String? toolGroupId,
    required String? toolName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkspaceToolByToolName, [], {
              #toolGroupId: toolGroupId,
              #toolName: toolName,
            }),
            returnValue: _i4.Future<_i2.WorkspaceToolEntity?>.value(),
          )
          as _i4.Future<_i2.WorkspaceToolEntity?>);

  @override
  _i4.Future<_i2.WorkspaceToolEntity> setToolEnabledById(
    String? id, {
    required bool? isEnabled,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setToolEnabledById,
              [id],
              {#isEnabled: isEnabled},
            ),
            returnValue: _i4.Future<_i2.WorkspaceToolEntity>.value(
              _FakeWorkspaceToolEntity_0(
                this,
                Invocation.method(
                  #setToolEnabledById,
                  [id],
                  {#isEnabled: isEnabled},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.WorkspaceToolEntity>);

  @override
  _i4.Future<List<_i2.WorkspaceToolEntity>> updateWorkspaceToolConfig(
    String? workspaceId,
    String? toolType,
    String? config,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkspaceToolConfig, [
              workspaceId,
              toolType,
              config,
            ]),
            returnValue: _i4.Future<List<_i2.WorkspaceToolEntity>>.value(
              <_i2.WorkspaceToolEntity>[],
            ),
          )
          as _i4.Future<List<_i2.WorkspaceToolEntity>>);

  @override
  _i4.Future<bool> isWorkspaceToolEnabled(
    String? workspaceId,
    String? toolType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isWorkspaceToolEnabled, [workspaceId, toolType]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String?> getWorkspaceToolConfig(
    String? workspaceId,
    String? toolType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkspaceToolConfig, [workspaceId, toolType]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> removeWorkspaceTool(String? workspaceId, String? toolType) =>
      (super.noSuchMethod(
            Invocation.method(#removeWorkspaceTool, [workspaceId, toolType]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> removeWorkspaceToolById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeWorkspaceToolById, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<int> getWorkspaceToolsCount(String? workspaceId) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkspaceToolsCount, [workspaceId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> getEnabledWorkspaceToolsCount(String? workspaceId) =>
      (super.noSuchMethod(
            Invocation.method(#getEnabledWorkspaceToolsCount, [workspaceId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> copyWorkspaceToolsToConversation(
    String? workspaceId,
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#copyWorkspaceToolsToConversation, [
              workspaceId,
              conversationId,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> validateWorkspaceToolSetting(
    String? workspaceId,
    String? toolType, {
    required bool? isEnabled,
    String? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #validateWorkspaceToolSetting,
              [workspaceId, toolType],
              {#isEnabled: isEnabled, #config: config},
            ),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.WorkspaceToolEntity> setToolPermissionMode(
    String? id, {
    required _i2.ToolPermissionMode? permissionMode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setToolPermissionMode,
              [id],
              {#permissionMode: permissionMode},
            ),
            returnValue: _i4.Future<_i2.WorkspaceToolEntity>.value(
              _FakeWorkspaceToolEntity_0(
                this,
                Invocation.method(
                  #setToolPermissionMode,
                  [id],
                  {#permissionMode: permissionMode},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.WorkspaceToolEntity>);
}
