// Mocks generated by Mockito 5.4.6 from annotations
// in auravibes_app/test/domain/usecases/tools/send_tool_responses_to_ai_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:auravibes_app/domain/entities/messages.dart' as _i2;
import 'package:auravibes_app/domain/enums/message_types.dart' as _i5;
import 'package:auravibes_app/domain/repositories/message_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMessageEntity_0 extends _i1.SmartFake implements _i2.MessageEntity {
  _FakeMessageEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageRepository extends _i1.Mock implements _i3.MessageRepository {
  MockMessageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.MessageEntity>> getMessagesByConversation(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByConversation, [conversationId]),
            returnValue: _i4.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i4.Future<List<_i2.MessageEntity>>);

  @override
  _i4.Future<List<_i2.MessageEntity>> getMessagesByConversationPaginated(
    String? conversationId,
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByConversationPaginated, [
              conversationId,
              limit,
              offset,
            ]),
            returnValue: _i4.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i4.Future<List<_i2.MessageEntity>>);

  @override
  _i4.Future<List<_i2.MessageEntity>> getMessagesByType(
    String? conversationId,
    _i5.MessageType? messageType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByType, [
              conversationId,
              messageType,
            ]),
            returnValue: _i4.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i4.Future<List<_i2.MessageEntity>>);

  @override
  _i4.Future<List<_i2.MessageEntity>> getUserMessages(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserMessages, [conversationId]),
            returnValue: _i4.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i4.Future<List<_i2.MessageEntity>>);

  @override
  _i4.Future<List<_i2.MessageEntity>> getSystemMessages(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSystemMessages, [conversationId]),
            returnValue: _i4.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i4.Future<List<_i2.MessageEntity>>);

  @override
  _i4.Future<_i2.MessageEntity?> getMessageById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageById, [id]),
            returnValue: _i4.Future<_i2.MessageEntity?>.value(),
          )
          as _i4.Future<_i2.MessageEntity?>);

  @override
  _i4.Future<_i2.MessageEntity> createMessage(_i2.MessageToCreate? message) =>
      (super.noSuchMethod(
            Invocation.method(#createMessage, [message]),
            returnValue: _i4.Future<_i2.MessageEntity>.value(
              _FakeMessageEntity_0(
                this,
                Invocation.method(#createMessage, [message]),
              ),
            ),
          )
          as _i4.Future<_i2.MessageEntity>);

  @override
  _i4.Future<_i2.MessageEntity> updateMessage(
    String? id,
    _i2.MessageToUpdate? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMessage, [id, message]),
            returnValue: _i4.Future<_i2.MessageEntity>.value(
              _FakeMessageEntity_0(
                this,
                Invocation.method(#updateMessage, [id, message]),
              ),
            ),
          )
          as _i4.Future<_i2.MessageEntity>);

  @override
  _i4.Future<_i2.MessageEntity?> appendToMessage(String? id, String? delta) =>
      (super.noSuchMethod(
            Invocation.method(#appendToMessage, [id, delta]),
            returnValue: _i4.Future<_i2.MessageEntity?>.value(),
          )
          as _i4.Future<_i2.MessageEntity?>);

  @override
  _i4.Future<bool> deleteMessage(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> messageExists(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#messageExists, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<_i2.MessageEntity>> getMessagesByStatus(
    String? conversationId,
    _i5.MessageStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByStatus, [conversationId, status]),
            returnValue: _i4.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i4.Future<List<_i2.MessageEntity>>);

  @override
  _i4.Future<int> getMessageCountByConversation(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageCountByConversation, [conversationId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<bool> validateMessage(_i2.MessageToCreate? message) =>
      (super.noSuchMethod(
            Invocation.method(#validateMessage, [message]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
