// Mocks generated by Mockito 5.4.6 from annotations
// in auravibes_app/test/data/repositories/conversation_tools_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:auravibes_app/domain/entities/workspace_tool.dart' as _i2;
import 'package:auravibes_app/domain/repositories/workspace_tools_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWorkspaceToolEntity_0 extends _i1.SmartFake
    implements _i2.WorkspaceToolEntity {
  _FakeWorkspaceToolEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WorkspaceToolsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkspaceToolsRepository extends _i1.Mock
    implements _i3.WorkspaceToolsRepository {
  MockWorkspaceToolsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.WorkspaceToolEntity>> getWorkspaceTools(
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkspaceTools, [workspaceId]),
            returnValue: _i4.Future<List<_i2.WorkspaceToolEntity>>.value(
              <_i2.WorkspaceToolEntity>[],
            ),
          )
          as _i4.Future<List<_i2.WorkspaceToolEntity>>);

  @override
  _i4.Future<List<_i2.WorkspaceToolEntity>> getEnabledWorkspaceTools(
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEnabledWorkspaceTools, [workspaceId]),
            returnValue: _i4.Future<List<_i2.WorkspaceToolEntity>>.value(
              <_i2.WorkspaceToolEntity>[],
            ),
          )
          as _i4.Future<List<_i2.WorkspaceToolEntity>>);

  @override
  _i4.Future<_i2.WorkspaceToolEntity?> getWorkspaceTool(
    String? workspaceId,
    String? toolType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkspaceTool, [workspaceId, toolType]),
            returnValue: _i4.Future<_i2.WorkspaceToolEntity?>.value(),
          )
          as _i4.Future<_i2.WorkspaceToolEntity?>);

  @override
  _i4.Future<_i2.WorkspaceToolEntity> setWorkspaceToolEnabled(
    String? workspaceId,
    String? toolType, {
    required bool? isEnabled,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setWorkspaceToolEnabled,
              [workspaceId, toolType],
              {#isEnabled: isEnabled},
            ),
            returnValue: _i4.Future<_i2.WorkspaceToolEntity>.value(
              _FakeWorkspaceToolEntity_0(
                this,
                Invocation.method(
                  #setWorkspaceToolEnabled,
                  [workspaceId, toolType],
                  {#isEnabled: isEnabled},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.WorkspaceToolEntity>);

  @override
  _i4.Future<List<_i2.WorkspaceToolEntity>> updateWorkspaceToolConfig(
    String? workspaceId,
    String? toolType,
    String? config,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkspaceToolConfig, [
              workspaceId,
              toolType,
              config,
            ]),
            returnValue: _i4.Future<List<_i2.WorkspaceToolEntity>>.value(
              <_i2.WorkspaceToolEntity>[],
            ),
          )
          as _i4.Future<List<_i2.WorkspaceToolEntity>>);

  @override
  _i4.Future<bool> isWorkspaceToolEnabled(
    String? workspaceId,
    String? toolType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isWorkspaceToolEnabled, [workspaceId, toolType]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String?> getWorkspaceToolConfig(
    String? workspaceId,
    String? toolType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkspaceToolConfig, [workspaceId, toolType]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> removeWorkspaceTool(String? workspaceId, String? toolType) =>
      (super.noSuchMethod(
            Invocation.method(#removeWorkspaceTool, [workspaceId, toolType]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> removeWorkspaceToolById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeWorkspaceToolById, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<int> getWorkspaceToolsCount(String? workspaceId) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkspaceToolsCount, [workspaceId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> getEnabledWorkspaceToolsCount(String? workspaceId) =>
      (super.noSuchMethod(
            Invocation.method(#getEnabledWorkspaceToolsCount, [workspaceId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> copyWorkspaceToolsToConversation(
    String? workspaceId,
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#copyWorkspaceToolsToConversation, [
              workspaceId,
              conversationId,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> validateWorkspaceToolSetting(
    String? workspaceId,
    String? toolType, {
    required bool? isEnabled,
    String? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #validateWorkspaceToolSetting,
              [workspaceId, toolType],
              {#isEnabled: isEnabled, #config: config},
            ),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.WorkspaceToolEntity> setToolPermissionMode(
    String? id, {
    required _i2.ToolPermissionMode? permissionMode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setToolPermissionMode,
              [id],
              {#permissionMode: permissionMode},
            ),
            returnValue: _i4.Future<_i2.WorkspaceToolEntity>.value(
              _FakeWorkspaceToolEntity_0(
                this,
                Invocation.method(
                  #setToolPermissionMode,
                  [id],
                  {#permissionMode: permissionMode},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.WorkspaceToolEntity>);
}
