reusables:
  - &release_tag
    instance_type: mac_mini_m2
    max_build_duration: 60
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'auravibes_app-v+([0-9]).+([0-9]).+([0-9])'
          include: true
scripts:
  - &script_setup_environment
    name: Setup Environment
    script: |
      echo PATH="$PATH":"$FLUTTER_ROOT/.pub-cache/bin" >> $CM_ENV
      echo PATH="$PATH":"$FLUTTER_ROOT/bin" >> $CM_ENV
  
  - &script_install_melos
    name: Install Melos
    script: |
      dart pub global activate melos

  - &script_melos_bootstrap
    name: Bootstrap Monorepo
    script: |
      echo "Bootstrapping monorepo packages..."
      melos bootstrap --verbose

  - &script_generate_code
    name: Generate
    script: |
      echo "Running generations..."
      melos generate
      melos localization

  
  - &script_parse_tag
    name: Parse Tag and Set Environment
    script: |
      # Parse tag to extract version and environment
      TAG_VERSION=${CM_TAG##*-v} # Remove '<package-name>-v' prefix
      
      if [[ $TAG_VERSION == *"-beta"* ]]; then
        FLAVOR="beta"
      else
        FLAVOR="prod"
      fi
      
      # Extract version from tag (1.2.3 or 1.2.3-beta.1)
      VERSION=${TAG_VERSION%%-*}
      echo "Version: $VERSION"
      
      # Set environment variables for build
      echo "BUILD_NAME=$VERSION" >> $CM_ENV
      
      # Set automatic build number
      echo "BUILD_NUMBER=$PROJECT_BUILD_NUMBER" >> $CM_ENV
      echo "FLAVOR=$FLAVOR" >> $CM_ENV
  - &script_install_cocoapods
    name: Install CocoaPods
    script: |
      echo "Installing CocoaPods dependencies..."
      find . -name "Podfile" -execdir pod install \;

workflows:
  # iOS Release Workflow
  release-ios:
    name: Release iOS
    <<: *release_tag
    environment:
      flutter: fvm
      groups:
        - github
      ios_signing:
        distribution_type: app_store
        bundle_identifier: me.auravibes.app
    integrations:
      app_store_connect: app_store_connect
    cache:
      cache_paths:
        - ~/.pub-cache
        - $FLUTTER_ROOT/.pub-cache
        - ~/.pub-cache/hosted
        - ~/Library/Caches/CocoaPods
    scripts:
      - *script_setup_environment
      - *script_install_melos
      - *script_melos_bootstrap
      - *script_generate_code
      - *script_parse_tag

      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles

      - *script_install_cocoapods

      - name: Build iOS IPA with Obfuscation and Split Debug Info
        script: |
          echo "Building iOS IPA..."
          echo "Build Name: $BUILD_NAME"
          echo "Build Number: $BUILD_NUMBER"
          echo "Flavor: $FLAVOR"
          
          cd apps/auravibes_app
          
          flutter build ipa --release \
            --flavor=$FLAVOR \
            --build-name=$BUILD_NAME \
            --build-number=$BUILD_NUMBER \
            --obfuscate \
            --export-options-plist=/Users/builder/export_options.plist \
            --split-debug-info=./ios/symbols

    artifacts:
      - apps/auravibes_app/build/ios/ipa/*.ipa
      - apps/auravibes_app/ios/symbols/**
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:      
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Beta Testers
        submit_to_app_store: false
      
      scripts:
        - name: Publish iOS artifacts to GitHub Release
          script: |
            if [ -z "${CM_TAG}" ]; then
              echo "Not a tag build, will not publish to GitHub release"
              exit 0
            fi
            cd apps/auravibes_app
            gh release upload "${CM_TAG}" build/ios/ipa/*.ipa --clobber

  # Android Release Workflow
  release-android:
    name: Release Android
    <<: *release_tag
    environment:
      flutter: fvm
      android_signing:
        - auravibes_keystore
      groups:
        - google_play
        - github
      vars:
        PACKAGE_NAME: "me.auravibes.app"
        GOOGLE_PLAY_TRACK: internal
    cache:
      cache_paths:
        - ~/.pub-cache
        - $FLUTTER_ROOT/.pub-cache
        - ~/.gradle/cache
    scripts:
      - *script_setup_environment
      - *script_install_melos
      - *script_melos_bootstrap
      - *script_generate_code
      - *script_parse_tag

      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/apps/auravibes_app/android/local.properties"

      - name: Build Android AAB with Obfuscation and Split Debug Info
        script: |
          echo "Building Android AAB..."
          echo "Build Name: $BUILD_NAME"
          echo "Build Number: $BUILD_NUMBER"
          echo "Flavor: $FLAVOR"
          echo "Package Name: $PACKAGE_NAME"
          echo "Track: $GOOGLE_PLAY_TRACK"
          
          cd apps/auravibes_app
          
          
          flutter build appbundle \
            --release \
            --flavor=$FLAVOR \
            --build-name=$BUILD_NAME \
            --build-number=$BUILD_NUMBER \
            --obfuscate \
            --split-debug-info=./android/symbols

    artifacts:
      - apps/auravibes_app/build/**/outputs/**/*.aab
      - apps/auravibes_app/build/**/outputs/**/mapping.txt
      - apps/auravibes_app/android/symbols/**
      - flutter_drive.log

    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true
      
      scripts:
        - name: Publish Android artifacts to GitHub Release
          script: |
            if [ -z "${CM_TAG}" ]; then
              echo "Not a tag build, will not publish to GitHub release"
              exit 0
            fi
            cd apps/auravibes_app
            gh release upload "${CM_TAG}" build/app/outputs/bundle/**/*.aab --clobber
