sonar.projectKey=auravibes-apps_auravibes
sonar.organization=auravibes-apps
sonar.projectName=auravibes
sonar.sourceEncoding=UTF-8

sonar.sources=apps,packages,widgetbook
sonar.tests=apps,packages,widgetbook

sonar.inclusions=**/*.dart
sonar.test.inclusions=**/test/**,**/integration_test/**,**/*_test.dart

sonar.exclusions=**/drift_worker.js,.specify/scripts/**,**/*.g.dart,**/*.freezed.dart,**/*.mocks.dart,**/test/**,**/integration_test/**,**/*_test.dart
sonar.coverage.exclusions=**/*.g.dart,**/*.freezed.dart,**/*.mocks.dart,**/drift_worker.js,.specify/scripts/**
sonar.cpd.exclusions=**/*.g.dart,**/*.freezed.dart,**/*.mocks.dart,**/drift_worker.js

sonar.dart.lcov.reportPaths=**/coverage/lcov.info

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=600
