// Mocks generated by Mockito 5.4.6 from annotations
// in auravibes_app/test/features/chats/notifiers/messages_streaming_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:auravibes_app/services/chatbot_service/chat_result.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeChatMessage_0 extends _i1.SmartFake implements _i2.ChatMessage {
  _FakeChatMessage_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$ChatResultCopyWith_1<T, $Res> extends _i1.SmartFake
    implements _i2.$ChatResultCopyWith<T, $Res> {
  _Fake$ChatResultCopyWith_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatResult].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatResult extends _i1.Mock
    implements _i2.ChatResult<_i2.ChatMessage> {
  @override
  _i2.ChatMessage get output =>
      (super.noSuchMethod(
            Invocation.getter(#output),
            returnValue: _FakeChatMessage_0(this, Invocation.getter(#output)),
            returnValueForMissingStub: _FakeChatMessage_0(
              this,
              Invocation.getter(#output),
            ),
          )
          as _i2.ChatMessage);

  @override
  _i2.FinishReason get finishReason =>
      (super.noSuchMethod(
            Invocation.getter(#finishReason),
            returnValue: _i2.FinishReason.stop,
            returnValueForMissingStub: _i2.FinishReason.stop,
          )
          as _i2.FinishReason);

  @override
  Map<String, dynamic> get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  List<_i2.ChatMessage> get messages =>
      (super.noSuchMethod(
            Invocation.getter(#messages),
            returnValue: <_i2.ChatMessage>[],
            returnValueForMissingStub: <_i2.ChatMessage>[],
          )
          as List<_i2.ChatMessage>);

  @override
  _i2.$ChatResultCopyWith<_i2.ChatMessage, _i2.ChatResult<_i2.ChatMessage>>
  get copyWith =>
      (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue:
                _Fake$ChatResultCopyWith_1<
                  _i2.ChatMessage,
                  _i2.ChatResult<_i2.ChatMessage>
                >(this, Invocation.getter(#copyWith)),
            returnValueForMissingStub:
                _Fake$ChatResultCopyWith_1<
                  _i2.ChatMessage,
                  _i2.ChatResult<_i2.ChatMessage>
                >(this, Invocation.getter(#copyWith)),
          )
          as _i2.$ChatResultCopyWith<
            _i2.ChatMessage,
            _i2.ChatResult<_i2.ChatMessage>
          >);
}
