// Mocks generated by Mockito 5.4.6 from annotations
// in auravibes_app/test/features/chats/notifiers/messages_streaming_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:dartantic_interface/src/chat/chat_message.dart' as _i3;
import 'package:dartantic_interface/src/chat/chat_result.dart' as _i2;
import 'package:dartantic_interface/src/model/model.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ChatResult].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatResult extends _i1.Mock
    implements _i2.ChatResult<_i3.ChatMessage> {
  @override
  List<_i3.ChatMessage> get messages =>
      (super.noSuchMethod(
            Invocation.getter(#messages),
            returnValue: <_i3.ChatMessage>[],
            returnValueForMissingStub: <_i3.ChatMessage>[],
          )
          as List<_i3.ChatMessage>);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#id)),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.getter(#id),
            ),
          )
          as String);

  @override
  _i3.ChatMessage get output =>
      (super.noSuchMethod(
            Invocation.getter(#output),
            returnValue: _i4.dummyValue<_i3.ChatMessage>(
              this,
              Invocation.getter(#output),
            ),
            returnValueForMissingStub: _i4.dummyValue<_i3.ChatMessage>(
              this,
              Invocation.getter(#output),
            ),
          )
          as _i3.ChatMessage);

  @override
  _i5.FinishReason get finishReason =>
      (super.noSuchMethod(
            Invocation.getter(#finishReason),
            returnValue: _i5.FinishReason.stop,
            returnValueForMissingStub: _i5.FinishReason.stop,
          )
          as _i5.FinishReason);

  @override
  Map<String, dynamic> get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
