name: auravibes_server
description: AuraVibes cloud workspace Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ^3.13.0

resolution: workspace

dependencies:
  async: ^2.13.0
  auravibes_engine:
    path: ../../packages/auravibes_engine
  cryptography: ^2.9.0
  genkit: ^0.15.1
  serverpod: 4.0.0-rc.2
  serverpod_auth_core_server: 4.0.0-beta.0
  serverpod_auth_idp_server: 4.0.0-beta.0

dev_dependencies:
  coverage: ^1.15.1
  lints: ">=3.0.0 <7.0.0"
  serverpod_test: 4.0.0-beta.0
  test: ^1.25.5

serverpod:
  scripts:
    # Starts the server and applies migrations
    start: dart bin/main.dart --apply-migrations
