// Mocks generated by Mockito 5.4.6 from annotations
// in auravibes_app/test/features/chats/usecases/continue_agent_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:auravibes_app/domain/entities/conversation_entity.dart' as _i4;
import 'package:auravibes_app/domain/entities/message_tool_call_entity.dart'
    as _i3;
import 'package:auravibes_app/domain/entities/tool_spec.dart' as _i10;
import 'package:auravibes_app/domain/entities/workspace_model_selection_entity.dart'
    as _i9;
import 'package:auravibes_app/domain/enums/message_type.dart' as _i12;
import 'package:auravibes_app/domain/repositories/conversation_repository.dart'
    as _i14;
import 'package:auravibes_app/domain/repositories/message_repository.dart'
    as _i5;
import 'package:auravibes_app/domain/repositories/workspace_model_selection_repository.dart'
    as _i13;
import 'package:auravibes_app/features/chats/usecases/select_prompt_messages_usecase.dart'
    as _i17;
import 'package:auravibes_app/features/tools/usecases/load_conversation_tool_specs_usecase.dart'
    as _i15;
import 'package:auravibes_app/services/chatbot_service/chat_result.dart' as _i8;
import 'package:auravibes_app/services/chatbot_service/chatbot_service.dart'
    as _i6;
import 'package:auravibes_app/services/encryption_service.dart' as _i2;
import 'package:auravibes_app/services/monitoring_service.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEncryptionService_0 extends _i1.SmartFake
    implements _i2.EncryptionService {
  _FakeEncryptionService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessageEntity_1 extends _i1.SmartFake implements _i3.MessageEntity {
  _FakeMessageEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConversationEntity_2 extends _i1.SmartFake
    implements _i4.ConversationEntity {
  _FakeConversationEntity_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessageRepository_3 extends _i1.SmartFake
    implements _i5.MessageRepository {
  _FakeMessageRepository_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatbotService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatbotService extends _i1.Mock implements _i6.ChatbotService {
  MockChatbotService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.EncryptionService get encryptionService =>
      (super.noSuchMethod(
            Invocation.getter(#encryptionService),
            returnValue: _FakeEncryptionService_0(
              this,
              Invocation.getter(#encryptionService),
            ),
          )
          as _i2.EncryptionService);

  @override
  set encryptionService(_i2.EncryptionService? value) => super.noSuchMethod(
    Invocation.setter(#encryptionService, value),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Stream<_i8.ChatResult<_i8.ChatMessage>> sendMessage(
    _i9.WorkspaceModelSelectionWithConnectionEntity? chatProvider,
    List<_i8.ChatMessage>? history, {
    List<_i10.ToolSpec>? tools,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessage,
              [chatProvider, history],
              {#tools: tools},
            ),
            returnValue: _i7.Stream<_i8.ChatResult<_i8.ChatMessage>>.empty(),
          )
          as _i7.Stream<_i8.ChatResult<_i8.ChatMessage>>);

  @override
  _i7.Future<String> generateTitle(
    _i9.WorkspaceModelSelectionWithConnectionEntity? chatProvider,
    String? firstMessage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateTitle, [chatProvider, firstMessage]),
            returnValue: _i7.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#generateTitle, [chatProvider, firstMessage]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Stream<String> streamTitle(
    _i9.WorkspaceModelSelectionWithConnectionEntity? chatProvider,
    String? firstMessage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#streamTitle, [chatProvider, firstMessage]),
            returnValue: _i7.Stream<String>.empty(),
          )
          as _i7.Stream<String>);
}

/// A class which mocks [MessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageRepository extends _i1.Mock implements _i5.MessageRepository {
  MockMessageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i3.MessageEntity>> getMessagesByConversation(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByConversation, [conversationId]),
            returnValue: _i7.Future<List<_i3.MessageEntity>>.value(
              <_i3.MessageEntity>[],
            ),
          )
          as _i7.Future<List<_i3.MessageEntity>>);

  @override
  _i7.Stream<List<_i3.MessageEntity>> watchMessagesByConversation(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchMessagesByConversation, [conversationId]),
            returnValue: _i7.Stream<List<_i3.MessageEntity>>.empty(),
          )
          as _i7.Stream<List<_i3.MessageEntity>>);

  @override
  _i7.Future<List<_i3.MessageEntity>> getMessagesByConversationPaginated(
    String? conversationId,
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByConversationPaginated, [
              conversationId,
              limit,
              offset,
            ]),
            returnValue: _i7.Future<List<_i3.MessageEntity>>.value(
              <_i3.MessageEntity>[],
            ),
          )
          as _i7.Future<List<_i3.MessageEntity>>);

  @override
  _i7.Future<List<_i3.MessageEntity>> getMessagesByType(
    String? conversationId,
    _i12.MessageType? messageType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByType, [
              conversationId,
              messageType,
            ]),
            returnValue: _i7.Future<List<_i3.MessageEntity>>.value(
              <_i3.MessageEntity>[],
            ),
          )
          as _i7.Future<List<_i3.MessageEntity>>);

  @override
  _i7.Future<List<_i3.MessageEntity>> getUserMessages(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserMessages, [conversationId]),
            returnValue: _i7.Future<List<_i3.MessageEntity>>.value(
              <_i3.MessageEntity>[],
            ),
          )
          as _i7.Future<List<_i3.MessageEntity>>);

  @override
  _i7.Future<List<_i3.MessageEntity>> getSystemMessages(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSystemMessages, [conversationId]),
            returnValue: _i7.Future<List<_i3.MessageEntity>>.value(
              <_i3.MessageEntity>[],
            ),
          )
          as _i7.Future<List<_i3.MessageEntity>>);

  @override
  _i7.Future<_i3.MessageEntity?> getMessageById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageById, [id]),
            returnValue: _i7.Future<_i3.MessageEntity?>.value(),
          )
          as _i7.Future<_i3.MessageEntity?>);

  @override
  _i7.Future<_i3.MessageEntity> createMessage(_i3.MessageToCreate? message) =>
      (super.noSuchMethod(
            Invocation.method(#createMessage, [message]),
            returnValue: _i7.Future<_i3.MessageEntity>.value(
              _FakeMessageEntity_1(
                this,
                Invocation.method(#createMessage, [message]),
              ),
            ),
          )
          as _i7.Future<_i3.MessageEntity>);

  @override
  _i7.Future<_i3.MessageEntity> patchMessage(
    String? id,
    _i3.MessagePatch? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#patchMessage, [id, message]),
            returnValue: _i7.Future<_i3.MessageEntity>.value(
              _FakeMessageEntity_1(
                this,
                Invocation.method(#patchMessage, [id, message]),
              ),
            ),
          )
          as _i7.Future<_i3.MessageEntity>);

  @override
  _i7.Future<bool> deleteMessage(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [id]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> messageExists(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#messageExists, [id]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<List<_i3.MessageEntity>> getMessagesByStatus(
    String? conversationId,
    _i12.MessageStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByStatus, [conversationId, status]),
            returnValue: _i7.Future<List<_i3.MessageEntity>>.value(
              <_i3.MessageEntity>[],
            ),
          )
          as _i7.Future<List<_i3.MessageEntity>>);

  @override
  _i7.Future<int> getMessageCountByConversation(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageCountByConversation, [conversationId]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<bool> validateMessage(_i3.MessageToCreate? message) =>
      (super.noSuchMethod(
            Invocation.method(#validateMessage, [message]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<_i3.MessageEntity?> getLatestCompactionSummary(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestCompactionSummary, [conversationId]),
            returnValue: _i7.Future<_i3.MessageEntity?>.value(),
          )
          as _i7.Future<_i3.MessageEntity?>);
}

/// A class which mocks [WorkspaceModelSelectionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkspaceModelSelectionRepository extends _i1.Mock
    implements _i13.WorkspaceModelSelectionRepository {
  MockWorkspaceModelSelectionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> createWorkspaceModelSelections(
    List<_i9.WorkspaceModelSelectionToCreate>? workspaceModelSelections,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createWorkspaceModelSelections, [
              workspaceModelSelections,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i9.WorkspaceModelSelectionWithConnectionEntity>>
  getWorkspaceModelSelections(_i9.WorkspaceModelSelectionFilter? filter) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkspaceModelSelections, [filter]),
            returnValue:
                _i7.Future<
                  List<_i9.WorkspaceModelSelectionWithConnectionEntity>
                >.value(<_i9.WorkspaceModelSelectionWithConnectionEntity>[]),
          )
          as _i7.Future<List<_i9.WorkspaceModelSelectionWithConnectionEntity>>);

  @override
  _i7.Stream<List<_i9.WorkspaceModelSelectionWithConnectionEntity>>
  watchWorkspaceModelSelections(_i9.WorkspaceModelSelectionFilter? filter) =>
      (super.noSuchMethod(
            Invocation.method(#watchWorkspaceModelSelections, [filter]),
            returnValue:
                _i7.Stream<
                  List<_i9.WorkspaceModelSelectionWithConnectionEntity>
                >.empty(),
          )
          as _i7.Stream<List<_i9.WorkspaceModelSelectionWithConnectionEntity>>);

  @override
  _i7.Future<_i9.WorkspaceModelSelectionWithConnectionEntity?>
  getWorkspaceModelSelectionById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkspaceModelSelectionById, [id]),
            returnValue:
                _i7.Future<
                  _i9.WorkspaceModelSelectionWithConnectionEntity?
                >.value(),
          )
          as _i7.Future<_i9.WorkspaceModelSelectionWithConnectionEntity?>);
}

/// A class which mocks [ConversationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationRepository extends _i1.Mock
    implements _i14.ConversationRepository {
  MockConversationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<List<_i4.ConversationEntity>> watchConversationsByWorkspace(
    String? workspaceId, {
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #watchConversationsByWorkspace,
              [workspaceId],
              {#limit: limit},
            ),
            returnValue: _i7.Stream<List<_i4.ConversationEntity>>.empty(),
          )
          as _i7.Stream<List<_i4.ConversationEntity>>);

  @override
  _i7.Stream<_i4.ConversationEntity?> watchConversationById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchConversationById, [id]),
            returnValue: _i7.Stream<_i4.ConversationEntity?>.empty(),
          )
          as _i7.Stream<_i4.ConversationEntity?>);

  @override
  _i7.Future<_i4.ConversationEntity?> getConversationById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationById, [id]),
            returnValue: _i7.Future<_i4.ConversationEntity?>.value(),
          )
          as _i7.Future<_i4.ConversationEntity?>);

  @override
  _i7.Future<_i4.ConversationEntity> createConversation(
    _i4.ConversationToCreate? conversation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createConversation, [conversation]),
            returnValue: _i7.Future<_i4.ConversationEntity>.value(
              _FakeConversationEntity_2(
                this,
                Invocation.method(#createConversation, [conversation]),
              ),
            ),
          )
          as _i7.Future<_i4.ConversationEntity>);

  @override
  _i7.Future<_i4.ConversationEntity> patchConversation(
    String? id,
    _i4.ConversationPatch? conversation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#patchConversation, [id, conversation]),
            returnValue: _i7.Future<_i4.ConversationEntity>.value(
              _FakeConversationEntity_2(
                this,
                Invocation.method(#patchConversation, [id, conversation]),
              ),
            ),
          )
          as _i7.Future<_i4.ConversationEntity>);

  @override
  _i7.Future<bool> deleteConversation(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [id]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);
}

/// A class which mocks [LoadConversationToolSpecsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadConversationToolSpecsUsecase extends _i1.Mock
    implements _i15.LoadConversationToolSpecsUsecase {
  MockLoadConversationToolSpecsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i10.ToolSpec>> call({
    required String? conversationId,
    required String? workspaceId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #conversationId: conversationId,
              #workspaceId: workspaceId,
            }),
            returnValue: _i7.Future<List<_i10.ToolSpec>>.value(
              <_i10.ToolSpec>[],
            ),
          )
          as _i7.Future<List<_i10.ToolSpec>>);
}

/// A class which mocks [MonitoringService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMonitoringService extends _i1.Mock implements _i16.MonitoringService {
  MockMonitoringService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get enableConsoleLogging =>
      (super.noSuchMethod(
            Invocation.getter(#enableConsoleLogging),
            returnValue: false,
          )
          as bool);

  @override
  void trackError(
    String? concept, {
    required Object? error,
    required StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #trackError,
      [concept],
      {#error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SelectPromptMessagesUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSelectPromptMessagesUsecase extends _i1.Mock
    implements _i17.SelectPromptMessagesUsecase {
  MockSelectPromptMessagesUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.MessageRepository get messageRepository =>
      (super.noSuchMethod(
            Invocation.getter(#messageRepository),
            returnValue: _FakeMessageRepository_3(
              this,
              Invocation.getter(#messageRepository),
            ),
          )
          as _i5.MessageRepository);

  @override
  _i7.Future<List<_i3.MessageEntity>> call(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [conversationId]),
            returnValue: _i7.Future<List<_i3.MessageEntity>>.value(
              <_i3.MessageEntity>[],
            ),
          )
          as _i7.Future<List<_i3.MessageEntity>>);
}
