// Mocks generated by Mockito 5.4.6 from annotations
// in auravibes_app/test/features/chats/usecases/generate_title_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:auravibes_app/domain/entities/conversation_entity.dart' as _i2;
import 'package:auravibes_app/domain/entities/tool_spec.dart' as _i10;
import 'package:auravibes_app/domain/entities/workspace_model_selection_entity.dart'
    as _i9;
import 'package:auravibes_app/domain/repositories/conversation_repository.dart'
    as _i5;
import 'package:auravibes_app/domain/repositories/model_connection_repository.dart'
    as _i3;
import 'package:auravibes_app/services/chatbot_service/chat_result.dart' as _i8;
import 'package:auravibes_app/services/chatbot_service/chatbot_service.dart'
    as _i7;
import 'package:auravibes_app/services/encryption_service.dart' as _i4;
import 'package:auravibes_app/services/monitoring_service.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeConversationEntity_0 extends _i1.SmartFake
    implements _i2.ConversationEntity {
  _FakeConversationEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeModelConnectionRepository_1 extends _i1.SmartFake
    implements _i3.ModelConnectionRepository {
  _FakeModelConnectionRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEncryptionService_2 extends _i1.SmartFake
    implements _i4.EncryptionService {
  _FakeEncryptionService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ConversationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationRepository extends _i1.Mock
    implements _i5.ConversationRepository {
  MockConversationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<List<_i2.ConversationEntity>> watchConversationsByWorkspace(
    String? workspaceId, {
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #watchConversationsByWorkspace,
              [workspaceId],
              {#limit: limit},
            ),
            returnValue: _i6.Stream<List<_i2.ConversationEntity>>.empty(),
          )
          as _i6.Stream<List<_i2.ConversationEntity>>);

  @override
  _i6.Stream<_i2.ConversationEntity?> watchConversationById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchConversationById, [id]),
            returnValue: _i6.Stream<_i2.ConversationEntity?>.empty(),
          )
          as _i6.Stream<_i2.ConversationEntity?>);

  @override
  _i6.Future<_i2.ConversationEntity?> getConversationById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationById, [id]),
            returnValue: _i6.Future<_i2.ConversationEntity?>.value(),
          )
          as _i6.Future<_i2.ConversationEntity?>);

  @override
  _i6.Future<_i2.ConversationEntity> createConversation(
    _i2.ConversationToCreate? conversation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createConversation, [conversation]),
            returnValue: _i6.Future<_i2.ConversationEntity>.value(
              _FakeConversationEntity_0(
                this,
                Invocation.method(#createConversation, [conversation]),
              ),
            ),
          )
          as _i6.Future<_i2.ConversationEntity>);

  @override
  _i6.Future<_i2.ConversationEntity> patchConversation(
    String? id,
    _i2.ConversationPatch? conversation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#patchConversation, [id, conversation]),
            returnValue: _i6.Future<_i2.ConversationEntity>.value(
              _FakeConversationEntity_0(
                this,
                Invocation.method(#patchConversation, [id, conversation]),
              ),
            ),
          )
          as _i6.Future<_i2.ConversationEntity>);

  @override
  _i6.Future<bool> deleteConversation(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [id]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [ChatbotService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatbotService extends _i1.Mock implements _i7.ChatbotService {
  MockChatbotService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ModelConnectionRepository get modelConnectionRepository =>
      (super.noSuchMethod(
            Invocation.getter(#modelConnectionRepository),
            returnValue: _FakeModelConnectionRepository_1(
              this,
              Invocation.getter(#modelConnectionRepository),
            ),
          )
          as _i3.ModelConnectionRepository);

  @override
  _i4.EncryptionService get encryptionService =>
      (super.noSuchMethod(
            Invocation.getter(#encryptionService),
            returnValue: _FakeEncryptionService_2(
              this,
              Invocation.getter(#encryptionService),
            ),
          )
          as _i4.EncryptionService);

  @override
  set modelConnectionRepository(_i3.ModelConnectionRepository? value) =>
      super.noSuchMethod(
        Invocation.setter(#modelConnectionRepository, value),
        returnValueForMissingStub: null,
      );

  @override
  set encryptionService(_i4.EncryptionService? value) => super.noSuchMethod(
    Invocation.setter(#encryptionService, value),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Stream<_i8.ChatResult<_i8.ChatMessage>> sendMessage(
    _i9.WorkspaceModelSelectionWithConnectionEntity? chatProvider,
    List<_i8.ChatMessage>? history, {
    List<_i10.ToolSpec>? tools,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessage,
              [chatProvider, history],
              {#tools: tools},
            ),
            returnValue: _i6.Stream<_i8.ChatResult<_i8.ChatMessage>>.empty(),
          )
          as _i6.Stream<_i8.ChatResult<_i8.ChatMessage>>);

  @override
  _i6.Future<String> generateTitle(
    _i9.WorkspaceModelSelectionWithConnectionEntity? chatProvider,
    String? firstMessage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateTitle, [chatProvider, firstMessage]),
            returnValue: _i6.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#generateTitle, [chatProvider, firstMessage]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Stream<String> streamTitle(
    _i9.WorkspaceModelSelectionWithConnectionEntity? chatProvider,
    String? firstMessage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#streamTitle, [chatProvider, firstMessage]),
            returnValue: _i6.Stream<String>.empty(),
          )
          as _i6.Stream<String>);
}

/// A class which mocks [MonitoringService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMonitoringService extends _i1.Mock implements _i12.MonitoringService {
  MockMonitoringService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get enableConsoleLogging =>
      (super.noSuchMethod(
            Invocation.getter(#enableConsoleLogging),
            returnValue: false,
          )
          as bool);

  @override
  void trackError(
    String? concept, {
    required Object? error,
    required StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #trackError,
      [concept],
      {#error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );
}
