// Mocks generated by Mockito 5.4.6 from annotations
// in auravibes_app/test/features/chats/usecases/resume_conversation_if_ready_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;

import 'package:auravibes_app/domain/entities/conversation.dart' as _i3;
import 'package:auravibes_app/domain/entities/messages.dart' as _i2;
import 'package:auravibes_app/domain/enums/message_types.dart' as _i14;
import 'package:auravibes_app/domain/repositories/conversation_repository.dart'
    as _i11;
import 'package:auravibes_app/domain/repositories/message_repository.dart'
    as _i5;
import 'package:auravibes_app/features/chats/providers/agent_cancellation_runtime_provider.dart'
    as _i8;
import 'package:auravibes_app/features/chats/providers/send_queue_runtime_provider.dart'
    as _i12;
import 'package:auravibes_app/features/chats/usecases/agent_iteration_context.dart'
    as _i18;
import 'package:auravibes_app/features/chats/usecases/agent_iteration_decision.dart'
    as _i16;
import 'package:auravibes_app/features/chats/usecases/continue_agent_usecase.dart'
    as _i9;
import 'package:auravibes_app/features/chats/usecases/run_agent_iteration_usecase.dart'
    as _i17;
import 'package:auravibes_app/features/tools/usecases/get_agent_iteration_decision_usecase.dart'
    as _i7;
import 'package:auravibes_app/features/tools/usecases/load_latest_message_tool_calls_usecase.dart'
    as _i4;
import 'package:auravibes_app/features/tools/usecases/resolve_tool_approval_decision_usecase.dart'
    as _i6;
import 'package:auravibes_app/features/tools/usecases/run_allowed_tools_usecase.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMessageEntity_0 extends _i1.SmartFake implements _i2.MessageEntity {
  _FakeMessageEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConversationEntity_1 extends _i1.SmartFake
    implements _i3.ConversationEntity {
  _FakeConversationEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoadLatestMessageToolCallsUsecase_2 extends _i1.SmartFake
    implements _i4.LoadLatestMessageToolCallsUsecase {
  _FakeLoadLatestMessageToolCallsUsecase_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeMessageRepository_3 extends _i1.SmartFake
    implements _i5.MessageRepository {
  _FakeMessageRepository_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResolveToolApprovalDecisionUsecase_4 extends _i1.SmartFake
    implements _i6.ResolveToolApprovalDecisionUsecase {
  _FakeResolveToolApprovalDecisionUsecase_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeGetAgentIterationDecisionUsecase_5 extends _i1.SmartFake
    implements _i7.GetAgentIterationDecisionUsecase {
  _FakeGetAgentIterationDecisionUsecase_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeAgentCancellationRuntime_6 extends _i1.SmartFake
    implements _i8.AgentCancellationRuntime {
  _FakeAgentCancellationRuntime_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeContinueAgentUsecase_7 extends _i1.SmartFake
    implements _i9.ContinueAgentUsecase {
  _FakeContinueAgentUsecase_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRunAllowedToolsUsecase_8 extends _i1.SmartFake
    implements _i10.RunAllowedToolsUsecase {
  _FakeRunAllowedToolsUsecase_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConversationRepository_9 extends _i1.SmartFake
    implements _i11.ConversationRepository {
  _FakeConversationRepository_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConversationSendQueueRuntime_10 extends _i1.SmartFake
    implements _i12.ConversationSendQueueRuntime {
  _FakeConversationSendQueueRuntime_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

/// A class which mocks [MessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageRepository extends _i1.Mock implements _i5.MessageRepository {
  MockMessageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<List<_i2.MessageEntity>> getMessagesByConversation(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByConversation, [conversationId]),
            returnValue: _i13.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i13.Future<List<_i2.MessageEntity>>);

  @override
  _i13.Stream<List<_i2.MessageEntity>> watchMessagesByConversation(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchMessagesByConversation, [conversationId]),
            returnValue: _i13.Stream<List<_i2.MessageEntity>>.empty(),
          )
          as _i13.Stream<List<_i2.MessageEntity>>);

  @override
  _i13.Future<List<_i2.MessageEntity>> getMessagesByConversationPaginated(
    String? conversationId,
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByConversationPaginated, [
              conversationId,
              limit,
              offset,
            ]),
            returnValue: _i13.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i13.Future<List<_i2.MessageEntity>>);

  @override
  _i13.Future<List<_i2.MessageEntity>> getMessagesByType(
    String? conversationId,
    _i14.MessageType? messageType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByType, [
              conversationId,
              messageType,
            ]),
            returnValue: _i13.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i13.Future<List<_i2.MessageEntity>>);

  @override
  _i13.Future<List<_i2.MessageEntity>> getUserMessages(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserMessages, [conversationId]),
            returnValue: _i13.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i13.Future<List<_i2.MessageEntity>>);

  @override
  _i13.Future<List<_i2.MessageEntity>> getSystemMessages(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSystemMessages, [conversationId]),
            returnValue: _i13.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i13.Future<List<_i2.MessageEntity>>);

  @override
  _i13.Future<_i2.MessageEntity?> getMessageById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageById, [id]),
            returnValue: _i13.Future<_i2.MessageEntity?>.value(),
          )
          as _i13.Future<_i2.MessageEntity?>);

  @override
  _i13.Future<_i2.MessageEntity> createMessage(_i2.MessageToCreate? message) =>
      (super.noSuchMethod(
            Invocation.method(#createMessage, [message]),
            returnValue: _i13.Future<_i2.MessageEntity>.value(
              _FakeMessageEntity_0(
                this,
                Invocation.method(#createMessage, [message]),
              ),
            ),
          )
          as _i13.Future<_i2.MessageEntity>);

  @override
  _i13.Future<_i2.MessageEntity> patchMessage(
    String? id,
    _i2.MessagePatch? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#patchMessage, [id, message]),
            returnValue: _i13.Future<_i2.MessageEntity>.value(
              _FakeMessageEntity_0(
                this,
                Invocation.method(#patchMessage, [id, message]),
              ),
            ),
          )
          as _i13.Future<_i2.MessageEntity>);

  @override
  _i13.Future<bool> deleteMessage(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [id]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<bool> messageExists(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#messageExists, [id]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<List<_i2.MessageEntity>> getMessagesByStatus(
    String? conversationId,
    _i14.MessageStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByStatus, [conversationId, status]),
            returnValue: _i13.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i13.Future<List<_i2.MessageEntity>>);

  @override
  _i13.Future<int> getMessageCountByConversation(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageCountByConversation, [conversationId]),
            returnValue: _i13.Future<int>.value(0),
          )
          as _i13.Future<int>);

  @override
  _i13.Future<bool> validateMessage(_i2.MessageToCreate? message) =>
      (super.noSuchMethod(
            Invocation.method(#validateMessage, [message]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);
}

/// A class which mocks [ConversationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationRepository extends _i1.Mock
    implements _i11.ConversationRepository {
  MockConversationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Stream<List<_i3.ConversationEntity>> watchConversationsByWorkspace(
    String? workspaceId, {
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #watchConversationsByWorkspace,
              [workspaceId],
              {#limit: limit},
            ),
            returnValue: _i13.Stream<List<_i3.ConversationEntity>>.empty(),
          )
          as _i13.Stream<List<_i3.ConversationEntity>>);

  @override
  _i13.Stream<_i3.ConversationEntity?> watchConversationById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchConversationById, [id]),
            returnValue: _i13.Stream<_i3.ConversationEntity?>.empty(),
          )
          as _i13.Stream<_i3.ConversationEntity?>);

  @override
  _i13.Future<_i3.ConversationEntity?> getConversationById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationById, [id]),
            returnValue: _i13.Future<_i3.ConversationEntity?>.value(),
          )
          as _i13.Future<_i3.ConversationEntity?>);

  @override
  _i13.Future<_i3.ConversationEntity> createConversation(
    _i3.ConversationToCreate? conversation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createConversation, [conversation]),
            returnValue: _i13.Future<_i3.ConversationEntity>.value(
              _FakeConversationEntity_1(
                this,
                Invocation.method(#createConversation, [conversation]),
              ),
            ),
          )
          as _i13.Future<_i3.ConversationEntity>);

  @override
  _i13.Future<_i3.ConversationEntity> patchConversation(
    String? id,
    _i3.ConversationPatch? conversation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#patchConversation, [id, conversation]),
            returnValue: _i13.Future<_i3.ConversationEntity>.value(
              _FakeConversationEntity_1(
                this,
                Invocation.method(#patchConversation, [id, conversation]),
              ),
            ),
          )
          as _i13.Future<_i3.ConversationEntity>);

  @override
  _i13.Future<bool> deleteConversation(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [id]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);
}

/// A class which mocks [RunAllowedToolsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRunAllowedToolsUsecase extends _i1.Mock
    implements _i10.RunAllowedToolsUsecase {
  MockRunAllowedToolsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.LoadLatestMessageToolCallsUsecase get loadLatestMessageToolCallsUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#loadLatestMessageToolCallsUsecase),
            returnValue: _FakeLoadLatestMessageToolCallsUsecase_2(
              this,
              Invocation.getter(#loadLatestMessageToolCallsUsecase),
            ),
          )
          as _i4.LoadLatestMessageToolCallsUsecase);

  @override
  _i5.MessageRepository get messageRepository =>
      (super.noSuchMethod(
            Invocation.getter(#messageRepository),
            returnValue: _FakeMessageRepository_3(
              this,
              Invocation.getter(#messageRepository),
            ),
          )
          as _i5.MessageRepository);

  @override
  _i6.ResolveToolApprovalDecisionUsecase get resolveToolApprovalDecision =>
      (super.noSuchMethod(
            Invocation.getter(#resolveToolApprovalDecision),
            returnValue: _FakeResolveToolApprovalDecisionUsecase_4(
              this,
              Invocation.getter(#resolveToolApprovalDecision),
            ),
          )
          as _i6.ResolveToolApprovalDecisionUsecase);

  @override
  _i10.McpToolCaller get mcpToolCaller =>
      (super.noSuchMethod(
            Invocation.getter(#mcpToolCaller),
            returnValue:
                ({
                  required Map<String, dynamic> arguments,
                  required String mcpServerId,
                  required String toolIdentifier,
                }) => _i13.Future<String>.value(
                  _i15.dummyValue<String>(
                    this,
                    Invocation.getter(#mcpToolCaller),
                  ),
                ),
          )
          as _i10.McpToolCaller);

  @override
  _i7.GetAgentIterationDecisionUsecase get getAgentIterationDecisionUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#getAgentIterationDecisionUsecase),
            returnValue: _FakeGetAgentIterationDecisionUsecase_5(
              this,
              Invocation.getter(#getAgentIterationDecisionUsecase),
            ),
          )
          as _i7.GetAgentIterationDecisionUsecase);

  @override
  _i8.AgentCancellationRuntime get agentCancellationRuntime =>
      (super.noSuchMethod(
            Invocation.getter(#agentCancellationRuntime),
            returnValue: _FakeAgentCancellationRuntime_6(
              this,
              Invocation.getter(#agentCancellationRuntime),
            ),
          )
          as _i8.AgentCancellationRuntime);

  @override
  _i13.Future<_i16.AgentIterationDecision> call({
    required String? conversationId,
    required String? workspaceId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #conversationId: conversationId,
              #workspaceId: workspaceId,
            }),
            returnValue: _i13.Future<_i16.AgentIterationDecision>.value(
              _i16.AgentIterationDecision.done,
            ),
          )
          as _i13.Future<_i16.AgentIterationDecision>);
}

/// A class which mocks [RunAgentIterationUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRunAgentIterationUsecase extends _i1.Mock
    implements _i17.RunAgentIterationUsecase {
  MockRunAgentIterationUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.ContinueAgentUsecase get continueAgentUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#continueAgentUsecase),
            returnValue: _FakeContinueAgentUsecase_7(
              this,
              Invocation.getter(#continueAgentUsecase),
            ),
          )
          as _i9.ContinueAgentUsecase);

  @override
  _i10.RunAllowedToolsUsecase get runAllowedToolsUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#runAllowedToolsUsecase),
            returnValue: _FakeRunAllowedToolsUsecase_8(
              this,
              Invocation.getter(#runAllowedToolsUsecase),
            ),
          )
          as _i10.RunAllowedToolsUsecase);

  @override
  _i11.ConversationRepository get conversationRepository =>
      (super.noSuchMethod(
            Invocation.getter(#conversationRepository),
            returnValue: _FakeConversationRepository_9(
              this,
              Invocation.getter(#conversationRepository),
            ),
          )
          as _i11.ConversationRepository);

  @override
  _i5.MessageRepository get messageRepository =>
      (super.noSuchMethod(
            Invocation.getter(#messageRepository),
            returnValue: _FakeMessageRepository_3(
              this,
              Invocation.getter(#messageRepository),
            ),
          )
          as _i5.MessageRepository);

  @override
  _i12.ConversationSendQueueRuntime get sendQueueRuntime =>
      (super.noSuchMethod(
            Invocation.getter(#sendQueueRuntime),
            returnValue: _FakeConversationSendQueueRuntime_10(
              this,
              Invocation.getter(#sendQueueRuntime),
            ),
          )
          as _i12.ConversationSendQueueRuntime);

  @override
  _i8.AgentCancellationRuntime get agentCancellationRuntime =>
      (super.noSuchMethod(
            Invocation.getter(#agentCancellationRuntime),
            returnValue: _FakeAgentCancellationRuntime_6(
              this,
              Invocation.getter(#agentCancellationRuntime),
            ),
          )
          as _i8.AgentCancellationRuntime);

  @override
  _i13.Future<_i16.AgentIterationDecision> call({
    required String? conversationId,
    _i18.AgentIterationContext? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #conversationId: conversationId,
              #context: context,
            }),
            returnValue: _i13.Future<_i16.AgentIterationDecision>.value(
              _i16.AgentIterationDecision.done,
            ),
          )
          as _i13.Future<_i16.AgentIterationDecision>);
}
