// Mocks generated by Mockito 5.4.6 from annotations
// in auravibes_app/test/features/chats/usecases/run_agent_iteration_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i16;

import 'package:auravibes_app/domain/entities/conversation.dart' as _i14;
import 'package:auravibes_app/domain/entities/messages.dart' as _i15;
import 'package:auravibes_app/domain/enums/message_types.dart' as _i21;
import 'package:auravibes_app/domain/repositories/conversation_repository.dart'
    as _i5;
import 'package:auravibes_app/domain/repositories/message_repository.dart'
    as _i3;
import 'package:auravibes_app/domain/repositories/workspace_model_selection_repository.dart'
    as _i4;
import 'package:auravibes_app/features/chats/providers/agent_cancellation_runtime_provider.dart'
    as _i8;
import 'package:auravibes_app/features/chats/providers/streaming_runtime_provider.dart'
    as _i7;
import 'package:auravibes_app/features/chats/usecases/agent_iteration_context.dart'
    as _i17;
import 'package:auravibes_app/features/chats/usecases/agent_iteration_decision.dart'
    as _i20;
import 'package:auravibes_app/features/chats/usecases/continue_agent_usecase.dart'
    as _i10;
import 'package:auravibes_app/features/tools/usecases/get_agent_iteration_decision_usecase.dart'
    as _i13;
import 'package:auravibes_app/features/tools/usecases/load_conversation_tool_specs_usecase.dart'
    as _i6;
import 'package:auravibes_app/features/tools/usecases/load_latest_message_tool_calls_usecase.dart'
    as _i11;
import 'package:auravibes_app/features/tools/usecases/resolve_tool_approval_decision_usecase.dart'
    as _i12;
import 'package:auravibes_app/features/tools/usecases/run_allowed_tools_usecase.dart'
    as _i18;
import 'package:auravibes_app/services/chatbot_service/chatbot_service.dart'
    as _i2;
import 'package:auravibes_app/services/monitoring_service.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i19;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeChatbotService_0 extends _i1.SmartFake
    implements _i2.ChatbotService {
  _FakeChatbotService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessageRepository_1 extends _i1.SmartFake
    implements _i3.MessageRepository {
  _FakeMessageRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWorkspaceModelSelectionRepository_2 extends _i1.SmartFake
    implements _i4.WorkspaceModelSelectionRepository {
  _FakeWorkspaceModelSelectionRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeConversationRepository_3 extends _i1.SmartFake
    implements _i5.ConversationRepository {
  _FakeConversationRepository_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoadConversationToolSpecsUsecase_4 extends _i1.SmartFake
    implements _i6.LoadConversationToolSpecsUsecase {
  _FakeLoadConversationToolSpecsUsecase_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeMessagesStreamingRuntime_5 extends _i1.SmartFake
    implements _i7.MessagesStreamingRuntime {
  _FakeMessagesStreamingRuntime_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConversationStreamingRuntime_6 extends _i1.SmartFake
    implements _i7.ConversationStreamingRuntime {
  _FakeConversationStreamingRuntime_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeAgentCancellationRuntime_7 extends _i1.SmartFake
    implements _i8.AgentCancellationRuntime {
  _FakeAgentCancellationRuntime_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMonitoringService_8 extends _i1.SmartFake
    implements _i9.MonitoringService {
  _FakeMonitoringService_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeContinueAgentResult_9 extends _i1.SmartFake
    implements _i10.ContinueAgentResult {
  _FakeContinueAgentResult_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoadLatestMessageToolCallsUsecase_10 extends _i1.SmartFake
    implements _i11.LoadLatestMessageToolCallsUsecase {
  _FakeLoadLatestMessageToolCallsUsecase_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeResolveToolApprovalDecisionUsecase_11 extends _i1.SmartFake
    implements _i12.ResolveToolApprovalDecisionUsecase {
  _FakeResolveToolApprovalDecisionUsecase_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeGetAgentIterationDecisionUsecase_12 extends _i1.SmartFake
    implements _i13.GetAgentIterationDecisionUsecase {
  _FakeGetAgentIterationDecisionUsecase_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeConversationEntity_13 extends _i1.SmartFake
    implements _i14.ConversationEntity {
  _FakeConversationEntity_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessageEntity_14 extends _i1.SmartFake
    implements _i15.MessageEntity {
  _FakeMessageEntity_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ContinueAgentUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockContinueAgentUsecase extends _i1.Mock
    implements _i10.ContinueAgentUsecase {
  MockContinueAgentUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ChatbotService get chatbotService =>
      (super.noSuchMethod(
            Invocation.getter(#chatbotService),
            returnValue: _FakeChatbotService_0(
              this,
              Invocation.getter(#chatbotService),
            ),
          )
          as _i2.ChatbotService);

  @override
  _i3.MessageRepository get messageRepository =>
      (super.noSuchMethod(
            Invocation.getter(#messageRepository),
            returnValue: _FakeMessageRepository_1(
              this,
              Invocation.getter(#messageRepository),
            ),
          )
          as _i3.MessageRepository);

  @override
  _i4.WorkspaceModelSelectionRepository
  get workspaceModelSelectionsRepository =>
      (super.noSuchMethod(
            Invocation.getter(#workspaceModelSelectionsRepository),
            returnValue: _FakeWorkspaceModelSelectionRepository_2(
              this,
              Invocation.getter(#workspaceModelSelectionsRepository),
            ),
          )
          as _i4.WorkspaceModelSelectionRepository);

  @override
  _i5.ConversationRepository get conversationRepository =>
      (super.noSuchMethod(
            Invocation.getter(#conversationRepository),
            returnValue: _FakeConversationRepository_3(
              this,
              Invocation.getter(#conversationRepository),
            ),
          )
          as _i5.ConversationRepository);

  @override
  _i6.LoadConversationToolSpecsUsecase get loadConversationToolSpecsUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#loadConversationToolSpecsUsecase),
            returnValue: _FakeLoadConversationToolSpecsUsecase_4(
              this,
              Invocation.getter(#loadConversationToolSpecsUsecase),
            ),
          )
          as _i6.LoadConversationToolSpecsUsecase);

  @override
  _i7.MessagesStreamingRuntime get messagesStreamingRuntime =>
      (super.noSuchMethod(
            Invocation.getter(#messagesStreamingRuntime),
            returnValue: _FakeMessagesStreamingRuntime_5(
              this,
              Invocation.getter(#messagesStreamingRuntime),
            ),
          )
          as _i7.MessagesStreamingRuntime);

  @override
  _i7.ConversationStreamingRuntime get conversationStreamingRuntime =>
      (super.noSuchMethod(
            Invocation.getter(#conversationStreamingRuntime),
            returnValue: _FakeConversationStreamingRuntime_6(
              this,
              Invocation.getter(#conversationStreamingRuntime),
            ),
          )
          as _i7.ConversationStreamingRuntime);

  @override
  _i8.AgentCancellationRuntime get agentCancellationRuntime =>
      (super.noSuchMethod(
            Invocation.getter(#agentCancellationRuntime),
            returnValue: _FakeAgentCancellationRuntime_7(
              this,
              Invocation.getter(#agentCancellationRuntime),
            ),
          )
          as _i8.AgentCancellationRuntime);

  @override
  _i9.MonitoringService get monitoringService =>
      (super.noSuchMethod(
            Invocation.getter(#monitoringService),
            returnValue: _FakeMonitoringService_8(
              this,
              Invocation.getter(#monitoringService),
            ),
          )
          as _i9.MonitoringService);

  @override
  _i16.Future<_i10.ContinueAgentResult> call({
    required String? conversationId,
    _i17.AgentIterationContext? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #conversationId: conversationId,
              #context: context,
            }),
            returnValue: _i16.Future<_i10.ContinueAgentResult>.value(
              _FakeContinueAgentResult_9(
                this,
                Invocation.method(#call, [], {
                  #conversationId: conversationId,
                  #context: context,
                }),
              ),
            ),
          )
          as _i16.Future<_i10.ContinueAgentResult>);
}

/// A class which mocks [RunAllowedToolsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRunAllowedToolsUsecase extends _i1.Mock
    implements _i18.RunAllowedToolsUsecase {
  MockRunAllowedToolsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.LoadLatestMessageToolCallsUsecase
  get loadLatestMessageToolCallsUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#loadLatestMessageToolCallsUsecase),
            returnValue: _FakeLoadLatestMessageToolCallsUsecase_10(
              this,
              Invocation.getter(#loadLatestMessageToolCallsUsecase),
            ),
          )
          as _i11.LoadLatestMessageToolCallsUsecase);

  @override
  _i3.MessageRepository get messageRepository =>
      (super.noSuchMethod(
            Invocation.getter(#messageRepository),
            returnValue: _FakeMessageRepository_1(
              this,
              Invocation.getter(#messageRepository),
            ),
          )
          as _i3.MessageRepository);

  @override
  _i12.ResolveToolApprovalDecisionUsecase get resolveToolApprovalDecision =>
      (super.noSuchMethod(
            Invocation.getter(#resolveToolApprovalDecision),
            returnValue: _FakeResolveToolApprovalDecisionUsecase_11(
              this,
              Invocation.getter(#resolveToolApprovalDecision),
            ),
          )
          as _i12.ResolveToolApprovalDecisionUsecase);

  @override
  _i18.McpToolCaller get mcpToolCaller =>
      (super.noSuchMethod(
            Invocation.getter(#mcpToolCaller),
            returnValue:
                ({
                  required Map<String, dynamic> arguments,
                  required String mcpServerId,
                  required String toolIdentifier,
                }) => _i16.Future<String>.value(
                  _i19.dummyValue<String>(
                    this,
                    Invocation.getter(#mcpToolCaller),
                  ),
                ),
          )
          as _i18.McpToolCaller);

  @override
  _i13.GetAgentIterationDecisionUsecase get getAgentIterationDecisionUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#getAgentIterationDecisionUsecase),
            returnValue: _FakeGetAgentIterationDecisionUsecase_12(
              this,
              Invocation.getter(#getAgentIterationDecisionUsecase),
            ),
          )
          as _i13.GetAgentIterationDecisionUsecase);

  @override
  _i8.AgentCancellationRuntime get agentCancellationRuntime =>
      (super.noSuchMethod(
            Invocation.getter(#agentCancellationRuntime),
            returnValue: _FakeAgentCancellationRuntime_7(
              this,
              Invocation.getter(#agentCancellationRuntime),
            ),
          )
          as _i8.AgentCancellationRuntime);

  @override
  _i16.Future<_i20.AgentIterationDecision> call({
    required String? conversationId,
    required String? workspaceId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #conversationId: conversationId,
              #workspaceId: workspaceId,
            }),
            returnValue: _i16.Future<_i20.AgentIterationDecision>.value(
              _i20.AgentIterationDecision.done,
            ),
          )
          as _i16.Future<_i20.AgentIterationDecision>);
}

/// A class which mocks [ConversationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationRepository extends _i1.Mock
    implements _i5.ConversationRepository {
  MockConversationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Stream<List<_i14.ConversationEntity>> watchConversationsByWorkspace(
    String? workspaceId, {
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #watchConversationsByWorkspace,
              [workspaceId],
              {#limit: limit},
            ),
            returnValue: _i16.Stream<List<_i14.ConversationEntity>>.empty(),
          )
          as _i16.Stream<List<_i14.ConversationEntity>>);

  @override
  _i16.Stream<_i14.ConversationEntity?> watchConversationById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchConversationById, [id]),
            returnValue: _i16.Stream<_i14.ConversationEntity?>.empty(),
          )
          as _i16.Stream<_i14.ConversationEntity?>);

  @override
  _i16.Future<_i14.ConversationEntity?> getConversationById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationById, [id]),
            returnValue: _i16.Future<_i14.ConversationEntity?>.value(),
          )
          as _i16.Future<_i14.ConversationEntity?>);

  @override
  _i16.Future<_i14.ConversationEntity> createConversation(
    _i14.ConversationToCreate? conversation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createConversation, [conversation]),
            returnValue: _i16.Future<_i14.ConversationEntity>.value(
              _FakeConversationEntity_13(
                this,
                Invocation.method(#createConversation, [conversation]),
              ),
            ),
          )
          as _i16.Future<_i14.ConversationEntity>);

  @override
  _i16.Future<_i14.ConversationEntity> patchConversation(
    String? id,
    _i14.ConversationPatch? conversation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#patchConversation, [id, conversation]),
            returnValue: _i16.Future<_i14.ConversationEntity>.value(
              _FakeConversationEntity_13(
                this,
                Invocation.method(#patchConversation, [id, conversation]),
              ),
            ),
          )
          as _i16.Future<_i14.ConversationEntity>);

  @override
  _i16.Future<bool> deleteConversation(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [id]),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);
}

/// A class which mocks [MessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageRepository extends _i1.Mock implements _i3.MessageRepository {
  MockMessageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<List<_i15.MessageEntity>> getMessagesByConversation(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByConversation, [conversationId]),
            returnValue: _i16.Future<List<_i15.MessageEntity>>.value(
              <_i15.MessageEntity>[],
            ),
          )
          as _i16.Future<List<_i15.MessageEntity>>);

  @override
  _i16.Stream<List<_i15.MessageEntity>> watchMessagesByConversation(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchMessagesByConversation, [conversationId]),
            returnValue: _i16.Stream<List<_i15.MessageEntity>>.empty(),
          )
          as _i16.Stream<List<_i15.MessageEntity>>);

  @override
  _i16.Future<List<_i15.MessageEntity>> getMessagesByConversationPaginated(
    String? conversationId,
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByConversationPaginated, [
              conversationId,
              limit,
              offset,
            ]),
            returnValue: _i16.Future<List<_i15.MessageEntity>>.value(
              <_i15.MessageEntity>[],
            ),
          )
          as _i16.Future<List<_i15.MessageEntity>>);

  @override
  _i16.Future<List<_i15.MessageEntity>> getMessagesByType(
    String? conversationId,
    _i21.MessageType? messageType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByType, [
              conversationId,
              messageType,
            ]),
            returnValue: _i16.Future<List<_i15.MessageEntity>>.value(
              <_i15.MessageEntity>[],
            ),
          )
          as _i16.Future<List<_i15.MessageEntity>>);

  @override
  _i16.Future<List<_i15.MessageEntity>> getUserMessages(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserMessages, [conversationId]),
            returnValue: _i16.Future<List<_i15.MessageEntity>>.value(
              <_i15.MessageEntity>[],
            ),
          )
          as _i16.Future<List<_i15.MessageEntity>>);

  @override
  _i16.Future<List<_i15.MessageEntity>> getSystemMessages(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSystemMessages, [conversationId]),
            returnValue: _i16.Future<List<_i15.MessageEntity>>.value(
              <_i15.MessageEntity>[],
            ),
          )
          as _i16.Future<List<_i15.MessageEntity>>);

  @override
  _i16.Future<_i15.MessageEntity?> getMessageById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageById, [id]),
            returnValue: _i16.Future<_i15.MessageEntity?>.value(),
          )
          as _i16.Future<_i15.MessageEntity?>);

  @override
  _i16.Future<_i15.MessageEntity> createMessage(
    _i15.MessageToCreate? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createMessage, [message]),
            returnValue: _i16.Future<_i15.MessageEntity>.value(
              _FakeMessageEntity_14(
                this,
                Invocation.method(#createMessage, [message]),
              ),
            ),
          )
          as _i16.Future<_i15.MessageEntity>);

  @override
  _i16.Future<_i15.MessageEntity> patchMessage(
    String? id,
    _i15.MessagePatch? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#patchMessage, [id, message]),
            returnValue: _i16.Future<_i15.MessageEntity>.value(
              _FakeMessageEntity_14(
                this,
                Invocation.method(#patchMessage, [id, message]),
              ),
            ),
          )
          as _i16.Future<_i15.MessageEntity>);

  @override
  _i16.Future<bool> deleteMessage(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [id]),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Future<bool> messageExists(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#messageExists, [id]),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Future<List<_i15.MessageEntity>> getMessagesByStatus(
    String? conversationId,
    _i21.MessageStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByStatus, [conversationId, status]),
            returnValue: _i16.Future<List<_i15.MessageEntity>>.value(
              <_i15.MessageEntity>[],
            ),
          )
          as _i16.Future<List<_i15.MessageEntity>>);

  @override
  _i16.Future<int> getMessageCountByConversation(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageCountByConversation, [conversationId]),
            returnValue: _i16.Future<int>.value(0),
          )
          as _i16.Future<int>);

  @override
  _i16.Future<bool> validateMessage(_i15.MessageToCreate? message) =>
      (super.noSuchMethod(
            Invocation.method(#validateMessage, [message]),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);
}
