// Mocks generated by Mockito 5.4.6 from annotations
// in auravibes_app/test/features/chats/usecases/send_new_message_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:auravibes_app/domain/entities/conversation.dart' as _i2;
import 'package:auravibes_app/domain/entities/workspace_model_selection_entities.dart'
    as _i13;
import 'package:auravibes_app/domain/repositories/conversation_repository.dart'
    as _i7;
import 'package:auravibes_app/domain/repositories/message_repository.dart'
    as _i4;
import 'package:auravibes_app/domain/repositories/workspace_model_selection_repository.dart'
    as _i12;
import 'package:auravibes_app/features/chats/providers/send_queue_runtime_provider.dart'
    as _i6;
import 'package:auravibes_app/features/chats/providers/streaming_runtime_provider.dart'
    as _i9;
import 'package:auravibes_app/features/chats/usecases/generate_title_usecase.dart'
    as _i15;
import 'package:auravibes_app/features/chats/usecases/get_conversation_busy_state_usecase.dart'
    as _i5;
import 'package:auravibes_app/features/chats/usecases/run_agent_iteration_usecase.dart'
    as _i3;
import 'package:auravibes_app/features/chats/usecases/send_message_usecase.dart'
    as _i14;
import 'package:auravibes_app/services/chatbot_service/chatbot_service.dart'
    as _i8;
import 'package:auravibes_app/services/monitoring_service.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeConversationEntity_0 extends _i1.SmartFake
    implements _i2.ConversationEntity {
  _FakeConversationEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRunAgentIterationUsecase_1 extends _i1.SmartFake
    implements _i3.RunAgentIterationUsecase {
  _FakeRunAgentIterationUsecase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessageRepository_2 extends _i1.SmartFake
    implements _i4.MessageRepository {
  _FakeMessageRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetConversationBusyStateUsecase_3 extends _i1.SmartFake
    implements _i5.GetConversationBusyStateUsecase {
  _FakeGetConversationBusyStateUsecase_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeConversationSendQueueRuntime_4 extends _i1.SmartFake
    implements _i6.ConversationSendQueueRuntime {
  _FakeConversationSendQueueRuntime_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeConversationRepository_5 extends _i1.SmartFake
    implements _i7.ConversationRepository {
  _FakeConversationRepository_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChatbotService_6 extends _i1.SmartFake
    implements _i8.ChatbotService {
  _FakeChatbotService_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTitlesStreamingRuntime_7 extends _i1.SmartFake
    implements _i9.TitlesStreamingRuntime {
  _FakeTitlesStreamingRuntime_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMonitoringService_8 extends _i1.SmartFake
    implements _i10.MonitoringService {
  _FakeMonitoringService_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ConversationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationRepository extends _i1.Mock
    implements _i7.ConversationRepository {
  MockConversationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Stream<List<_i2.ConversationEntity>> watchConversationsByWorkspace(
    String? workspaceId, {
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #watchConversationsByWorkspace,
              [workspaceId],
              {#limit: limit},
            ),
            returnValue: _i11.Stream<List<_i2.ConversationEntity>>.empty(),
          )
          as _i11.Stream<List<_i2.ConversationEntity>>);

  @override
  _i11.Stream<_i2.ConversationEntity?> watchConversationById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchConversationById, [id]),
            returnValue: _i11.Stream<_i2.ConversationEntity?>.empty(),
          )
          as _i11.Stream<_i2.ConversationEntity?>);

  @override
  _i11.Future<_i2.ConversationEntity?> getConversationById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationById, [id]),
            returnValue: _i11.Future<_i2.ConversationEntity?>.value(),
          )
          as _i11.Future<_i2.ConversationEntity?>);

  @override
  _i11.Future<_i2.ConversationEntity> createConversation(
    _i2.ConversationToCreate? conversation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createConversation, [conversation]),
            returnValue: _i11.Future<_i2.ConversationEntity>.value(
              _FakeConversationEntity_0(
                this,
                Invocation.method(#createConversation, [conversation]),
              ),
            ),
          )
          as _i11.Future<_i2.ConversationEntity>);

  @override
  _i11.Future<_i2.ConversationEntity> patchConversation(
    String? id,
    _i2.ConversationPatch? conversation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#patchConversation, [id, conversation]),
            returnValue: _i11.Future<_i2.ConversationEntity>.value(
              _FakeConversationEntity_0(
                this,
                Invocation.method(#patchConversation, [id, conversation]),
              ),
            ),
          )
          as _i11.Future<_i2.ConversationEntity>);

  @override
  _i11.Future<bool> deleteConversation(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [id]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);
}

/// A class which mocks [WorkspaceModelSelectionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkspaceModelSelectionRepository extends _i1.Mock
    implements _i12.WorkspaceModelSelectionRepository {
  MockWorkspaceModelSelectionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<void> createWorkspaceModelSelections(
    List<_i13.WorkspaceModelSelectionToCreate>? workspaceModelSelections,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createWorkspaceModelSelections, [
              workspaceModelSelections,
            ]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<List<_i13.WorkspaceModelSelectionWithConnectionEntity>>
  getWorkspaceModelSelections(_i13.WorkspaceModelSelectionFilter? filter) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkspaceModelSelections, [filter]),
            returnValue:
                _i11.Future<
                  List<_i13.WorkspaceModelSelectionWithConnectionEntity>
                >.value(<_i13.WorkspaceModelSelectionWithConnectionEntity>[]),
          )
          as _i11.Future<
            List<_i13.WorkspaceModelSelectionWithConnectionEntity>
          >);

  @override
  _i11.Stream<List<_i13.WorkspaceModelSelectionWithConnectionEntity>>
  watchWorkspaceModelSelections(_i13.WorkspaceModelSelectionFilter? filter) =>
      (super.noSuchMethod(
            Invocation.method(#watchWorkspaceModelSelections, [filter]),
            returnValue:
                _i11.Stream<
                  List<_i13.WorkspaceModelSelectionWithConnectionEntity>
                >.empty(),
          )
          as _i11.Stream<
            List<_i13.WorkspaceModelSelectionWithConnectionEntity>
          >);

  @override
  _i11.Future<_i13.WorkspaceModelSelectionWithConnectionEntity?>
  getWorkspaceModelSelectionById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkspaceModelSelectionById, [id]),
            returnValue:
                _i11.Future<
                  _i13.WorkspaceModelSelectionWithConnectionEntity?
                >.value(),
          )
          as _i11.Future<_i13.WorkspaceModelSelectionWithConnectionEntity?>);
}

/// A class which mocks [SendMessageUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendMessageUsecase extends _i1.Mock
    implements _i14.SendMessageUsecase {
  MockSendMessageUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.RunAgentIterationUsecase get runAgentIterationUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#runAgentIterationUsecase),
            returnValue: _FakeRunAgentIterationUsecase_1(
              this,
              Invocation.getter(#runAgentIterationUsecase),
            ),
          )
          as _i3.RunAgentIterationUsecase);

  @override
  _i4.MessageRepository get messageRepository =>
      (super.noSuchMethod(
            Invocation.getter(#messageRepository),
            returnValue: _FakeMessageRepository_2(
              this,
              Invocation.getter(#messageRepository),
            ),
          )
          as _i4.MessageRepository);

  @override
  _i5.GetConversationBusyStateUsecase get getConversationBusyStateUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#getConversationBusyStateUsecase),
            returnValue: _FakeGetConversationBusyStateUsecase_3(
              this,
              Invocation.getter(#getConversationBusyStateUsecase),
            ),
          )
          as _i5.GetConversationBusyStateUsecase);

  @override
  _i6.ConversationSendQueueRuntime get sendQueueRuntime =>
      (super.noSuchMethod(
            Invocation.getter(#sendQueueRuntime),
            returnValue: _FakeConversationSendQueueRuntime_4(
              this,
              Invocation.getter(#sendQueueRuntime),
            ),
          )
          as _i6.ConversationSendQueueRuntime);

  @override
  _i11.Future<void> call({
    required String? conversationId,
    required String? content,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #conversationId: conversationId,
              #content: content,
            }),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [GenerateTitleUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGenerateTitleUsecase extends _i1.Mock
    implements _i15.GenerateTitleUsecase {
  MockGenerateTitleUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.ConversationRepository get conversationRepo =>
      (super.noSuchMethod(
            Invocation.getter(#conversationRepo),
            returnValue: _FakeConversationRepository_5(
              this,
              Invocation.getter(#conversationRepo),
            ),
          )
          as _i7.ConversationRepository);

  @override
  _i8.ChatbotService get chatbotService =>
      (super.noSuchMethod(
            Invocation.getter(#chatbotService),
            returnValue: _FakeChatbotService_6(
              this,
              Invocation.getter(#chatbotService),
            ),
          )
          as _i8.ChatbotService);

  @override
  _i9.TitlesStreamingRuntime get titlesStreamingRuntime =>
      (super.noSuchMethod(
            Invocation.getter(#titlesStreamingRuntime),
            returnValue: _FakeTitlesStreamingRuntime_7(
              this,
              Invocation.getter(#titlesStreamingRuntime),
            ),
          )
          as _i9.TitlesStreamingRuntime);

  @override
  _i10.MonitoringService get monitoringService =>
      (super.noSuchMethod(
            Invocation.getter(#monitoringService),
            returnValue: _FakeMonitoringService_8(
              this,
              Invocation.getter(#monitoringService),
            ),
          )
          as _i10.MonitoringService);

  @override
  void call({
    required String? conversationId,
    required String? firstMessage,
    required _i13.WorkspaceModelSelectionWithConnectionEntity?
    workspaceModelSelection,
  }) => super.noSuchMethod(
    Invocation.method(#call, [], {
      #conversationId: conversationId,
      #firstMessage: firstMessage,
      #workspaceModelSelection: workspaceModelSelection,
    }),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MonitoringService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMonitoringService extends _i1.Mock implements _i10.MonitoringService {
  MockMonitoringService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void trackError(
    String? concept, {
    required Object? error,
    required StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #trackError,
      [concept],
      {#error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );
}
