// Mocks generated by Mockito 5.4.6 from annotations
// in auravibes_app/test/features/chats/usecases/send_message_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;

import 'package:auravibes_app/domain/entities/messages.dart' as _i8;
import 'package:auravibes_app/domain/enums/message_types.dart' as _i15;
import 'package:auravibes_app/domain/repositories/conversation_repository.dart'
    as _i4;
import 'package:auravibes_app/domain/repositories/message_repository.dart'
    as _i5;
import 'package:auravibes_app/features/chats/providers/agent_cancellation_runtime_provider.dart'
    as _i7;
import 'package:auravibes_app/features/chats/providers/send_queue_runtime_provider.dart'
    as _i6;
import 'package:auravibes_app/features/chats/providers/streaming_runtime_provider.dart'
    as _i9;
import 'package:auravibes_app/features/chats/usecases/agent_iteration_context.dart'
    as _i14;
import 'package:auravibes_app/features/chats/usecases/agent_iteration_decision.dart'
    as _i13;
import 'package:auravibes_app/features/chats/usecases/continue_agent_usecase.dart'
    as _i2;
import 'package:auravibes_app/features/chats/usecases/get_conversation_busy_state_usecase.dart'
    as _i10;
import 'package:auravibes_app/features/chats/usecases/run_agent_iteration_usecase.dart'
    as _i11;
import 'package:auravibes_app/features/tools/usecases/run_allowed_tools_usecase.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeContinueAgentUsecase_0 extends _i1.SmartFake
    implements _i2.ContinueAgentUsecase {
  _FakeContinueAgentUsecase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRunAllowedToolsUsecase_1 extends _i1.SmartFake
    implements _i3.RunAllowedToolsUsecase {
  _FakeRunAllowedToolsUsecase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConversationRepository_2 extends _i1.SmartFake
    implements _i4.ConversationRepository {
  _FakeConversationRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessageRepository_3 extends _i1.SmartFake
    implements _i5.MessageRepository {
  _FakeMessageRepository_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConversationSendQueueRuntime_4 extends _i1.SmartFake
    implements _i6.ConversationSendQueueRuntime {
  _FakeConversationSendQueueRuntime_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeAgentCancellationRuntime_5 extends _i1.SmartFake
    implements _i7.AgentCancellationRuntime {
  _FakeAgentCancellationRuntime_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessageEntity_6 extends _i1.SmartFake implements _i8.MessageEntity {
  _FakeMessageEntity_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConversationStreamingRuntime_7 extends _i1.SmartFake
    implements _i9.ConversationStreamingRuntime {
  _FakeConversationStreamingRuntime_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeConversationBusyState_8 extends _i1.SmartFake
    implements _i10.ConversationBusyState {
  _FakeConversationBusyState_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RunAgentIterationUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRunAgentIterationUsecase extends _i1.Mock
    implements _i11.RunAgentIterationUsecase {
  MockRunAgentIterationUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ContinueAgentUsecase get continueAgentUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#continueAgentUsecase),
            returnValue: _FakeContinueAgentUsecase_0(
              this,
              Invocation.getter(#continueAgentUsecase),
            ),
          )
          as _i2.ContinueAgentUsecase);

  @override
  _i3.RunAllowedToolsUsecase get runAllowedToolsUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#runAllowedToolsUsecase),
            returnValue: _FakeRunAllowedToolsUsecase_1(
              this,
              Invocation.getter(#runAllowedToolsUsecase),
            ),
          )
          as _i3.RunAllowedToolsUsecase);

  @override
  _i4.ConversationRepository get conversationRepository =>
      (super.noSuchMethod(
            Invocation.getter(#conversationRepository),
            returnValue: _FakeConversationRepository_2(
              this,
              Invocation.getter(#conversationRepository),
            ),
          )
          as _i4.ConversationRepository);

  @override
  _i5.MessageRepository get messageRepository =>
      (super.noSuchMethod(
            Invocation.getter(#messageRepository),
            returnValue: _FakeMessageRepository_3(
              this,
              Invocation.getter(#messageRepository),
            ),
          )
          as _i5.MessageRepository);

  @override
  _i6.ConversationSendQueueRuntime get sendQueueRuntime =>
      (super.noSuchMethod(
            Invocation.getter(#sendQueueRuntime),
            returnValue: _FakeConversationSendQueueRuntime_4(
              this,
              Invocation.getter(#sendQueueRuntime),
            ),
          )
          as _i6.ConversationSendQueueRuntime);

  @override
  _i7.AgentCancellationRuntime get agentCancellationRuntime =>
      (super.noSuchMethod(
            Invocation.getter(#agentCancellationRuntime),
            returnValue: _FakeAgentCancellationRuntime_5(
              this,
              Invocation.getter(#agentCancellationRuntime),
            ),
          )
          as _i7.AgentCancellationRuntime);

  @override
  _i12.Future<_i13.AgentIterationDecision> call({
    required String? conversationId,
    _i14.AgentIterationContext? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #conversationId: conversationId,
              #context: context,
            }),
            returnValue: _i12.Future<_i13.AgentIterationDecision>.value(
              _i13.AgentIterationDecision.done,
            ),
          )
          as _i12.Future<_i13.AgentIterationDecision>);
}

/// A class which mocks [MessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageRepository extends _i1.Mock implements _i5.MessageRepository {
  MockMessageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<List<_i8.MessageEntity>> getMessagesByConversation(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByConversation, [conversationId]),
            returnValue: _i12.Future<List<_i8.MessageEntity>>.value(
              <_i8.MessageEntity>[],
            ),
          )
          as _i12.Future<List<_i8.MessageEntity>>);

  @override
  _i12.Stream<List<_i8.MessageEntity>> watchMessagesByConversation(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchMessagesByConversation, [conversationId]),
            returnValue: _i12.Stream<List<_i8.MessageEntity>>.empty(),
          )
          as _i12.Stream<List<_i8.MessageEntity>>);

  @override
  _i12.Future<List<_i8.MessageEntity>> getMessagesByConversationPaginated(
    String? conversationId,
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByConversationPaginated, [
              conversationId,
              limit,
              offset,
            ]),
            returnValue: _i12.Future<List<_i8.MessageEntity>>.value(
              <_i8.MessageEntity>[],
            ),
          )
          as _i12.Future<List<_i8.MessageEntity>>);

  @override
  _i12.Future<List<_i8.MessageEntity>> getMessagesByType(
    String? conversationId,
    _i15.MessageType? messageType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByType, [
              conversationId,
              messageType,
            ]),
            returnValue: _i12.Future<List<_i8.MessageEntity>>.value(
              <_i8.MessageEntity>[],
            ),
          )
          as _i12.Future<List<_i8.MessageEntity>>);

  @override
  _i12.Future<List<_i8.MessageEntity>> getUserMessages(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserMessages, [conversationId]),
            returnValue: _i12.Future<List<_i8.MessageEntity>>.value(
              <_i8.MessageEntity>[],
            ),
          )
          as _i12.Future<List<_i8.MessageEntity>>);

  @override
  _i12.Future<List<_i8.MessageEntity>> getSystemMessages(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSystemMessages, [conversationId]),
            returnValue: _i12.Future<List<_i8.MessageEntity>>.value(
              <_i8.MessageEntity>[],
            ),
          )
          as _i12.Future<List<_i8.MessageEntity>>);

  @override
  _i12.Future<_i8.MessageEntity?> getMessageById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageById, [id]),
            returnValue: _i12.Future<_i8.MessageEntity?>.value(),
          )
          as _i12.Future<_i8.MessageEntity?>);

  @override
  _i12.Future<_i8.MessageEntity> createMessage(_i8.MessageToCreate? message) =>
      (super.noSuchMethod(
            Invocation.method(#createMessage, [message]),
            returnValue: _i12.Future<_i8.MessageEntity>.value(
              _FakeMessageEntity_6(
                this,
                Invocation.method(#createMessage, [message]),
              ),
            ),
          )
          as _i12.Future<_i8.MessageEntity>);

  @override
  _i12.Future<_i8.MessageEntity> patchMessage(
    String? id,
    _i8.MessagePatch? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#patchMessage, [id, message]),
            returnValue: _i12.Future<_i8.MessageEntity>.value(
              _FakeMessageEntity_6(
                this,
                Invocation.method(#patchMessage, [id, message]),
              ),
            ),
          )
          as _i12.Future<_i8.MessageEntity>);

  @override
  _i12.Future<bool> deleteMessage(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [id]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> messageExists(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#messageExists, [id]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<List<_i8.MessageEntity>> getMessagesByStatus(
    String? conversationId,
    _i15.MessageStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByStatus, [conversationId, status]),
            returnValue: _i12.Future<List<_i8.MessageEntity>>.value(
              <_i8.MessageEntity>[],
            ),
          )
          as _i12.Future<List<_i8.MessageEntity>>);

  @override
  _i12.Future<int> getMessageCountByConversation(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageCountByConversation, [conversationId]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<bool> validateMessage(_i8.MessageToCreate? message) =>
      (super.noSuchMethod(
            Invocation.method(#validateMessage, [message]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);
}

/// A class which mocks [GetConversationBusyStateUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetConversationBusyStateUsecase extends _i1.Mock
    implements _i10.GetConversationBusyStateUsecase {
  MockGetConversationBusyStateUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.MessageRepository get messageRepository =>
      (super.noSuchMethod(
            Invocation.getter(#messageRepository),
            returnValue: _FakeMessageRepository_3(
              this,
              Invocation.getter(#messageRepository),
            ),
          )
          as _i5.MessageRepository);

  @override
  _i9.ConversationStreamingRuntime get conversationStreamingRuntime =>
      (super.noSuchMethod(
            Invocation.getter(#conversationStreamingRuntime),
            returnValue: _FakeConversationStreamingRuntime_7(
              this,
              Invocation.getter(#conversationStreamingRuntime),
            ),
          )
          as _i9.ConversationStreamingRuntime);

  @override
  _i12.Future<_i10.ConversationBusyState> call({
    required String? conversationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#conversationId: conversationId}),
            returnValue: _i12.Future<_i10.ConversationBusyState>.value(
              _FakeConversationBusyState_8(
                this,
                Invocation.method(#call, [], {#conversationId: conversationId}),
              ),
            ),
          )
          as _i12.Future<_i10.ConversationBusyState>);
}
