// Mocks generated by Mockito 5.4.6 from annotations
// in auravibes_app/test/services/model_sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:auravibes_app/domain/entities/api_model.dart' as _i6;
import 'package:auravibes_app/domain/entities/api_model_provider.dart' as _i5;
import 'package:auravibes_app/domain/repositories/api_model_repository.dart'
    as _i3;
import 'package:auravibes_app/services/model_api_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeModelApiResponse_0 extends _i1.SmartFake
    implements _i2.ModelApiResponse {
  _FakeModelApiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeModelApiStatus_1 extends _i1.SmartFake
    implements _i2.ModelApiStatus {
  _FakeModelApiStatus_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiModelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiModelRepository extends _i1.Mock
    implements _i3.ApiModelRepository {
  MockApiModelRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.ApiModelProviderEntity>> getAllProviders() =>
      (super.noSuchMethod(
            Invocation.method(#getAllProviders, []),
            returnValue: _i4.Future<List<_i5.ApiModelProviderEntity>>.value(
              <_i5.ApiModelProviderEntity>[],
            ),
          )
          as _i4.Future<List<_i5.ApiModelProviderEntity>>);

  @override
  _i4.Future<List<_i5.ApiModelProviderEntity>> getProvidersByType(
    String? type,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProvidersByType, [type]),
            returnValue: _i4.Future<List<_i5.ApiModelProviderEntity>>.value(
              <_i5.ApiModelProviderEntity>[],
            ),
          )
          as _i4.Future<List<_i5.ApiModelProviderEntity>>);

  @override
  _i4.Future<List<_i6.ApiModelEntity>> getAllModels() =>
      (super.noSuchMethod(
            Invocation.method(#getAllModels, []),
            returnValue: _i4.Future<List<_i6.ApiModelEntity>>.value(
              <_i6.ApiModelEntity>[],
            ),
          )
          as _i4.Future<List<_i6.ApiModelEntity>>);

  @override
  _i4.Future<_i6.ApiModelEntity?> getModelByProviderAndModelId(
    String? providerId,
    String? modelId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getModelByProviderAndModelId, [
              providerId,
              modelId,
            ]),
            returnValue: _i4.Future<_i6.ApiModelEntity?>.value(),
          )
          as _i4.Future<_i6.ApiModelEntity?>);

  @override
  _i4.Future<List<_i6.ApiModelEntity>> getModelsByProvider(
    String? providerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getModelsByProvider, [providerId]),
            returnValue: _i4.Future<List<_i6.ApiModelEntity>>.value(
              <_i6.ApiModelEntity>[],
            ),
          )
          as _i4.Future<List<_i6.ApiModelEntity>>);

  @override
  _i4.Future<List<_i5.ApiModelProviderEntity>> batchUpsertProviders(
    List<_i5.ApiModelProviderEntity>? providers,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#batchUpsertProviders, [providers]),
            returnValue: _i4.Future<List<_i5.ApiModelProviderEntity>>.value(
              <_i5.ApiModelProviderEntity>[],
            ),
          )
          as _i4.Future<List<_i5.ApiModelProviderEntity>>);

  @override
  _i4.Future<List<_i6.ApiModelEntity>> batchUpsertModels(
    List<_i6.ApiModelEntity>? models,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#batchUpsertModels, [models]),
            returnValue: _i4.Future<List<_i6.ApiModelEntity>>.value(
              <_i6.ApiModelEntity>[],
            ),
          )
          as _i4.Future<List<_i6.ApiModelEntity>>);

  @override
  _i4.Future<int> deleteAllData() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllData, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}

/// A class which mocks [ModelApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockModelApiService extends _i1.Mock implements _i2.ModelApiService {
  MockModelApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ModelApiResponse> fetchAllModels() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllModels, []),
            returnValue: _i4.Future<_i2.ModelApiResponse>.value(
              _FakeModelApiResponse_0(
                this,
                Invocation.method(#fetchAllModels, []),
              ),
            ),
          )
          as _i4.Future<_i2.ModelApiResponse>);

  @override
  _i4.Future<_i2.ModelApiStatus> getApiStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getApiStatus, []),
            returnValue: _i4.Future<_i2.ModelApiStatus>.value(
              _FakeModelApiStatus_1(this, Invocation.method(#getApiStatus, [])),
            ),
          )
          as _i4.Future<_i2.ModelApiStatus>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
