// Mocks generated by Mockito 5.4.6 from annotations
// in auravibes_app/test/features/tools/usecases/approve_tool_call_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:auravibes_app/domain/entities/conversation_tool_entity.dart'
    as _i8;
import 'package:auravibes_app/domain/entities/message_tool_call_entity.dart'
    as _i2;
import 'package:auravibes_app/domain/entities/tool_permission_mode.dart' as _i3;
import 'package:auravibes_app/domain/entities/tools_group_entity.dart' as _i11;
import 'package:auravibes_app/domain/enums/message_type.dart' as _i6;
import 'package:auravibes_app/domain/enums/tool_permission_result.dart' as _i9;
import 'package:auravibes_app/domain/repositories/conversation_tools_repository.dart'
    as _i7;
import 'package:auravibes_app/domain/repositories/message_repository.dart'
    as _i4;
import 'package:auravibes_app/domain/repositories/tools_groups_repository.dart'
    as _i10;
import 'package:auravibes_app/domain/repositories/workspace_tools_repository.dart'
    as _i12;
import 'package:auravibes_app/features/chats/usecases/resume_conversation_if_ready_usecase.dart'
    as _i15;
import 'package:auravibes_app/services/tools/models/resolved_tool_type.dart'
    as _i14;
import 'package:auravibes_app/services/tools/tool_resolver_service.dart'
    as _i13;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMessageEntity_0 extends _i1.SmartFake implements _i2.MessageEntity {
  _FakeMessageEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWorkspaceToolEntity_1 extends _i1.SmartFake
    implements _i3.WorkspaceToolEntity {
  _FakeWorkspaceToolEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageRepository extends _i1.Mock implements _i4.MessageRepository {
  MockMessageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.MessageEntity>> getMessagesByConversation(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByConversation, [conversationId]),
            returnValue: _i5.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i5.Future<List<_i2.MessageEntity>>);

  @override
  _i5.Stream<List<_i2.MessageEntity>> watchMessagesByConversation(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchMessagesByConversation, [conversationId]),
            returnValue: _i5.Stream<List<_i2.MessageEntity>>.empty(),
          )
          as _i5.Stream<List<_i2.MessageEntity>>);

  @override
  _i5.Future<List<_i2.MessageEntity>> getMessagesByConversationPaginated(
    String? conversationId,
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByConversationPaginated, [
              conversationId,
              limit,
              offset,
            ]),
            returnValue: _i5.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i5.Future<List<_i2.MessageEntity>>);

  @override
  _i5.Future<List<_i2.MessageEntity>> getMessagesByType(
    String? conversationId,
    _i6.MessageType? messageType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByType, [
              conversationId,
              messageType,
            ]),
            returnValue: _i5.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i5.Future<List<_i2.MessageEntity>>);

  @override
  _i5.Future<List<_i2.MessageEntity>> getUserMessages(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserMessages, [conversationId]),
            returnValue: _i5.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i5.Future<List<_i2.MessageEntity>>);

  @override
  _i5.Future<List<_i2.MessageEntity>> getSystemMessages(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSystemMessages, [conversationId]),
            returnValue: _i5.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i5.Future<List<_i2.MessageEntity>>);

  @override
  _i5.Future<_i2.MessageEntity?> getMessageById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageById, [id]),
            returnValue: _i5.Future<_i2.MessageEntity?>.value(),
          )
          as _i5.Future<_i2.MessageEntity?>);

  @override
  _i5.Future<_i2.MessageEntity> createMessage(_i2.MessageToCreate? message) =>
      (super.noSuchMethod(
            Invocation.method(#createMessage, [message]),
            returnValue: _i5.Future<_i2.MessageEntity>.value(
              _FakeMessageEntity_0(
                this,
                Invocation.method(#createMessage, [message]),
              ),
            ),
          )
          as _i5.Future<_i2.MessageEntity>);

  @override
  _i5.Future<_i2.MessageEntity> patchMessage(
    String? id,
    _i2.MessagePatch? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#patchMessage, [id, message]),
            returnValue: _i5.Future<_i2.MessageEntity>.value(
              _FakeMessageEntity_0(
                this,
                Invocation.method(#patchMessage, [id, message]),
              ),
            ),
          )
          as _i5.Future<_i2.MessageEntity>);

  @override
  _i5.Future<bool> deleteMessage(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> messageExists(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#messageExists, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<_i2.MessageEntity>> getMessagesByStatus(
    String? conversationId,
    _i6.MessageStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByStatus, [conversationId, status]),
            returnValue: _i5.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i5.Future<List<_i2.MessageEntity>>);

  @override
  _i5.Future<int> getMessageCountByConversation(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageCountByConversation, [conversationId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<bool> validateMessage(_i2.MessageToCreate? message) =>
      (super.noSuchMethod(
            Invocation.method(#validateMessage, [message]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i2.MessageEntity?> getLatestCompactionSummary(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestCompactionSummary, [conversationId]),
            returnValue: _i5.Future<_i2.MessageEntity?>.value(),
          )
          as _i5.Future<_i2.MessageEntity?>);
}

/// A class which mocks [ConversationToolsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationToolsRepository extends _i1.Mock
    implements _i7.ConversationToolsRepository {
  MockConversationToolsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i8.ConversationToolEntity>> getConversationTools(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationTools, [conversationId]),
            returnValue: _i5.Future<List<_i8.ConversationToolEntity>>.value(
              <_i8.ConversationToolEntity>[],
            ),
          )
          as _i5.Future<List<_i8.ConversationToolEntity>>);

  @override
  _i5.Future<List<_i8.ConversationToolEntity>> getEnabledConversationTools(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEnabledConversationTools, [conversationId]),
            returnValue: _i5.Future<List<_i8.ConversationToolEntity>>.value(
              <_i8.ConversationToolEntity>[],
            ),
          )
          as _i5.Future<List<_i8.ConversationToolEntity>>);

  @override
  _i5.Future<_i8.ConversationToolEntity?> getConversationTool(
    String? conversationId,
    String? toolId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationTool, [conversationId, toolId]),
            returnValue: _i5.Future<_i8.ConversationToolEntity?>.value(),
          )
          as _i5.Future<_i8.ConversationToolEntity?>);

  @override
  _i5.Future<bool> setConversationToolEnabled(
    String? conversationId,
    String? toolId, {
    required bool? isEnabled,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setConversationToolEnabled,
              [conversationId, toolId],
              {#isEnabled: isEnabled},
            ),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> setConversationToolsDisabled(
    String? conversationId,
    List<String>? toolIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setConversationToolsDisabled, [
              conversationId,
              toolIds,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> setConversationToolPermission(
    String? conversationId,
    String? toolId, {
    required _i3.ToolPermissionMode? permissionMode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setConversationToolPermission,
              [conversationId, toolId],
              {#permissionMode: permissionMode},
            ),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> toggleConversationTool(
    String? conversationId,
    String? toolId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleConversationTool, [
              conversationId,
              toolId,
            ]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> isConversationToolEnabled(
    String? conversationId,
    String? toolId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isConversationToolEnabled, [
              conversationId,
              toolId,
            ]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> removeConversationTool(
    String? conversationId,
    String? toolId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeConversationTool, [
              conversationId,
              toolId,
            ]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<int> getConversationToolsCount(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationToolsCount, [conversationId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> getEnabledConversationToolsCount(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getEnabledConversationToolsCount, [
              conversationId,
            ]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> copyConversationTools(
    String? sourceConversationId,
    String? targetConversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#copyConversationTools, [
              sourceConversationId,
              targetConversationId,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> validateConversationToolSetting(
    String? conversationId,
    String? toolId, {
    required bool? isEnabled,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #validateConversationToolSetting,
              [conversationId, toolId],
              {#isEnabled: isEnabled},
            ),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> isToolAvailableForConversation(
    String? conversationId,
    String? workspaceId,
    String? toolId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isToolAvailableForConversation, [
              conversationId,
              workspaceId,
              toolId,
            ]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<String>> getAvailableToolsForConversation(
    String? conversationId,
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableToolsForConversation, [
              conversationId,
              workspaceId,
            ]),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<List<_i3.WorkspaceToolEntity>>
  getAvailableToolEntitiesForConversation(
    String? conversationId,
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableToolEntitiesForConversation, [
              conversationId,
              workspaceId,
            ]),
            returnValue: _i5.Future<List<_i3.WorkspaceToolEntity>>.value(
              <_i3.WorkspaceToolEntity>[],
            ),
          )
          as _i5.Future<List<_i3.WorkspaceToolEntity>>);

  @override
  _i5.Future<_i9.ToolPermissionResult> checkToolPermission({
    required String? conversationId,
    required String? workspaceId,
    required String? toolId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#checkToolPermission, [], {
              #conversationId: conversationId,
              #workspaceId: workspaceId,
              #toolId: toolId,
            }),
            returnValue: _i5.Future<_i9.ToolPermissionResult>.value(
              _i9.ToolPermissionResult.granted,
            ),
          )
          as _i5.Future<_i9.ToolPermissionResult>);
}

/// A class which mocks [ToolsGroupsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockToolsGroupsRepository extends _i1.Mock
    implements _i10.ToolsGroupsRepository {
  MockToolsGroupsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i11.ToolsGroupEntity>> getToolsGroupsForWorkspace(
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getToolsGroupsForWorkspace, [workspaceId]),
            returnValue: _i5.Future<List<_i11.ToolsGroupEntity>>.value(
              <_i11.ToolsGroupEntity>[],
            ),
          )
          as _i5.Future<List<_i11.ToolsGroupEntity>>);

  @override
  _i5.Future<_i11.ToolsGroupEntity?> getToolsGroupById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getToolsGroupById, [id]),
            returnValue: _i5.Future<_i11.ToolsGroupEntity?>.value(),
          )
          as _i5.Future<_i11.ToolsGroupEntity?>);

  @override
  _i5.Future<_i11.ToolsGroupEntity?> getToolsGroupByMcpServerId(
    String? mcpServerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getToolsGroupByMcpServerId, [mcpServerId]),
            returnValue: _i5.Future<_i11.ToolsGroupEntity?>.value(),
          )
          as _i5.Future<_i11.ToolsGroupEntity?>);

  @override
  _i5.Future<bool> setToolsGroupEnabled(
    String? groupId, {
    required bool? isEnabled,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setToolsGroupEnabled,
              [groupId],
              {#isEnabled: isEnabled},
            ),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteToolsGroup(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteToolsGroup, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [WorkspaceToolsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkspaceToolsRepository extends _i1.Mock
    implements _i12.WorkspaceToolsRepository {
  MockWorkspaceToolsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.WorkspaceToolEntity>> getWorkspaceTools(
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkspaceTools, [workspaceId]),
            returnValue: _i5.Future<List<_i3.WorkspaceToolEntity>>.value(
              <_i3.WorkspaceToolEntity>[],
            ),
          )
          as _i5.Future<List<_i3.WorkspaceToolEntity>>);

  @override
  _i5.Future<List<_i3.WorkspaceToolEntity>> getEnabledWorkspaceTools(
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEnabledWorkspaceTools, [workspaceId]),
            returnValue: _i5.Future<List<_i3.WorkspaceToolEntity>>.value(
              <_i3.WorkspaceToolEntity>[],
            ),
          )
          as _i5.Future<List<_i3.WorkspaceToolEntity>>);

  @override
  _i5.Future<_i3.WorkspaceToolEntity?> getWorkspaceTool(
    String? workspaceId,
    String? toolType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkspaceTool, [workspaceId, toolType]),
            returnValue: _i5.Future<_i3.WorkspaceToolEntity?>.value(),
          )
          as _i5.Future<_i3.WorkspaceToolEntity?>);

  @override
  _i5.Future<_i3.WorkspaceToolEntity> setWorkspaceToolEnabled(
    String? workspaceId,
    String? toolType, {
    required bool? isEnabled,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setWorkspaceToolEnabled,
              [workspaceId, toolType],
              {#isEnabled: isEnabled},
            ),
            returnValue: _i5.Future<_i3.WorkspaceToolEntity>.value(
              _FakeWorkspaceToolEntity_1(
                this,
                Invocation.method(
                  #setWorkspaceToolEnabled,
                  [workspaceId, toolType],
                  {#isEnabled: isEnabled},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.WorkspaceToolEntity>);

  @override
  _i5.Future<_i3.WorkspaceToolEntity?> getWorkspaceToolByToolName({
    required String? toolGroupId,
    required String? toolName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkspaceToolByToolName, [], {
              #toolGroupId: toolGroupId,
              #toolName: toolName,
            }),
            returnValue: _i5.Future<_i3.WorkspaceToolEntity?>.value(),
          )
          as _i5.Future<_i3.WorkspaceToolEntity?>);

  @override
  _i5.Future<_i3.WorkspaceToolEntity> setToolEnabledById(
    String? id, {
    required bool? isEnabled,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setToolEnabledById,
              [id],
              {#isEnabled: isEnabled},
            ),
            returnValue: _i5.Future<_i3.WorkspaceToolEntity>.value(
              _FakeWorkspaceToolEntity_1(
                this,
                Invocation.method(
                  #setToolEnabledById,
                  [id],
                  {#isEnabled: isEnabled},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.WorkspaceToolEntity>);

  @override
  _i5.Future<List<_i3.WorkspaceToolEntity>> patchWorkspaceToolConfig(
    String? workspaceId,
    String? toolType,
    String? config,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#patchWorkspaceToolConfig, [
              workspaceId,
              toolType,
              config,
            ]),
            returnValue: _i5.Future<List<_i3.WorkspaceToolEntity>>.value(
              <_i3.WorkspaceToolEntity>[],
            ),
          )
          as _i5.Future<List<_i3.WorkspaceToolEntity>>);

  @override
  _i5.Future<bool> isWorkspaceToolEnabled(
    String? workspaceId,
    String? toolType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isWorkspaceToolEnabled, [workspaceId, toolType]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<String?> getWorkspaceToolConfig(
    String? workspaceId,
    String? toolType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkspaceToolConfig, [workspaceId, toolType]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<bool> removeWorkspaceTool(String? workspaceId, String? toolType) =>
      (super.noSuchMethod(
            Invocation.method(#removeWorkspaceTool, [workspaceId, toolType]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> removeWorkspaceToolById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeWorkspaceToolById, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<int> getWorkspaceToolsCount(String? workspaceId) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkspaceToolsCount, [workspaceId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> getEnabledWorkspaceToolsCount(String? workspaceId) =>
      (super.noSuchMethod(
            Invocation.method(#getEnabledWorkspaceToolsCount, [workspaceId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> copyWorkspaceToolsToConversation(
    String? workspaceId,
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#copyWorkspaceToolsToConversation, [
              workspaceId,
              conversationId,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> validateWorkspaceToolSetting(
    String? workspaceId,
    String? toolType, {
    required bool? isEnabled,
    String? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #validateWorkspaceToolSetting,
              [workspaceId, toolType],
              {#isEnabled: isEnabled, #config: config},
            ),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i3.WorkspaceToolEntity> setToolPermissionMode(
    String? id, {
    required _i3.ToolPermissionMode? permissionMode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setToolPermissionMode,
              [id],
              {#permissionMode: permissionMode},
            ),
            returnValue: _i5.Future<_i3.WorkspaceToolEntity>.value(
              _FakeWorkspaceToolEntity_1(
                this,
                Invocation.method(
                  #setToolPermissionMode,
                  [id],
                  {#permissionMode: permissionMode},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.WorkspaceToolEntity>);
}

/// A class which mocks [ToolResolverService].
///
/// See the documentation for Mockito's code generation for more information.
class MockToolResolverService extends _i1.Mock
    implements _i13.ToolResolverService {
  MockToolResolverService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.ResolvedTool? resolveTool(String? compositeToolName) =>
      (super.noSuchMethod(Invocation.method(#resolveTool, [compositeToolName]))
          as _i14.ResolvedTool?);
}

/// A class which mocks [ResumeConversationIfReadyUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResumeConversationIfReadyUsecase extends _i1.Mock
    implements _i15.ResumeConversationIfReadyUsecase {
  MockResumeConversationIfReadyUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> call({required String? messageId}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#messageId: messageId}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
