// GENERATED CODE - DO NOT MODIFY BY HAND

// dart format off
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_import, prefer_relative_imports, directives_ordering, unused_element, strict_raw_type
// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:widgetbook/widgetbook.dart' as _widgetbook;
import 'package:widgetbook_workspace/aura_ui/auravibes_alert_dialog.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_alert_dialog_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_app_bar.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_app_bar_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_badge.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_badge_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_button.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_button_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_button_group_action.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_button_group_action_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_button_group_multi.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_button_group_multi_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_button_group_single.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_button_group_single_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_card.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_card_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_checkbox_focus.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_checkbox_focus_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_checkbox_list_tile.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_checkbox_list_tile_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_checkbox_single.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_checkbox_single_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_choice_picker.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_choice_picker_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_confirm_dialog.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_confirm_dialog_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_container.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_container_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_date_time_input.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_date_time_input_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_divider.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_divider_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_dropdown_selector.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_dropdown_selector_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_floating_action_button.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_floating_action_button_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_icon.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_icon_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_icon_button.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_icon_button_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_image.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_image_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_input.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_input_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_linear_progress_indicator.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_linear_progress_indicator_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_list.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_list_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_loading_overlay.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_loading_overlay_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_message_bubble.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_message_bubble_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_message_status.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_message_status_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_modal.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_modal_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_popup_menu.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_popup_menu_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_popup_menu_button.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_popup_menu_button_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_pressable.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_pressable_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_radio.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_radio_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_radio_group.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_radio_group_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_radio_list_tile.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_radio_list_tile_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_screen.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_screen_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_selectable_text.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_selectable_text_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_sidebar.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_sidebar_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_slider.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_slider_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_snackbar.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_snackbar_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_spinner.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_spinner_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_switch.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_switch_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_tabs_basic.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_tabs_basic_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_tabs_selector.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_tabs_selector_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_text.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_text_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_tile.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_tile_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_tooltip.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_tooltip_stories;
import 'package:widgetbook_workspace/aura_ui/auravibes_typing_indicator.stories.dart' as _widgetbook_workspace_aura_ui_auravibes_typing_indicator_stories;

final components = <_widgetbook.Component>[
  _widgetbook_workspace_aura_ui_auravibes_alert_dialog_stories.AlertDialogDemoComponent,
  _widgetbook_workspace_aura_ui_auravibes_app_bar_stories.AppBarDemoComponent,
  _widgetbook_workspace_aura_ui_auravibes_badge_stories.AuraBadgeComponent,
  _widgetbook_workspace_aura_ui_auravibes_button_stories.AuraButtonComponent,
  _widgetbook_workspace_aura_ui_auravibes_button_group_action_stories.ActionDemoComponent,
  _widgetbook_workspace_aura_ui_auravibes_button_group_multi_stories.MultiSelectionDemoComponent,
  _widgetbook_workspace_aura_ui_auravibes_button_group_single_stories.SingleSelectionDemoComponent,
  _widgetbook_workspace_aura_ui_auravibes_card_stories.CardDemoComponent,
  _widgetbook_workspace_aura_ui_auravibes_checkbox_focus_stories.AuraCheckboxComponent,
  _widgetbook_workspace_aura_ui_auravibes_checkbox_list_tile_stories.CheckboxListTileDemoComponent,
  _widgetbook_workspace_aura_ui_auravibes_checkbox_single_stories.SingleCheckboxDemoComponent,
  _widgetbook_workspace_aura_ui_auravibes_choice_picker_stories.ChoicePickerDemoComponent,
  _widgetbook_workspace_aura_ui_auravibes_confirm_dialog_stories.ConfirmDialogDemoComponent,
  _widgetbook_workspace_aura_ui_auravibes_container_stories.AuraContainerComponent,
  _widgetbook_workspace_aura_ui_auravibes_date_time_input_stories.DateTimeInputDemoComponent,
  _widgetbook_workspace_aura_ui_auravibes_divider_stories.AuraDividerComponent,
  _widgetbook_workspace_aura_ui_auravibes_dropdown_selector_stories.DropdownDemoComponent,
  _widgetbook_workspace_aura_ui_auravibes_floating_action_button_stories.AuraFloatingActionButtonComponent,
  _widgetbook_workspace_aura_ui_auravibes_icon_stories.AuraIconComponent,
  _widgetbook_workspace_aura_ui_auravibes_icon_button_stories.AuraIconButtonComponent,
  _widgetbook_workspace_aura_ui_auravibes_image_stories.AuraImageComponent,
  _widgetbook_workspace_aura_ui_auravibes_input_stories.AuraInputComponent,
  _widgetbook_workspace_aura_ui_auravibes_linear_progress_indicator_stories.AuraLinearProgressIndicatorComponent,
  _widgetbook_workspace_aura_ui_auravibes_list_stories.AuraListComponent,
  _widgetbook_workspace_aura_ui_auravibes_loading_overlay_stories.LoadingOverlayDemoComponent,
  _widgetbook_workspace_aura_ui_auravibes_message_bubble_stories.MessageBubbleDemoComponent,
  _widgetbook_workspace_aura_ui_auravibes_message_status_stories.AuraMessageStatusComponent,
  _widgetbook_workspace_aura_ui_auravibes_modal_stories.AuraModalComponent,
  _widgetbook_workspace_aura_ui_auravibes_popup_menu_stories.AuraPopupMenuComponent,
  _widgetbook_workspace_aura_ui_auravibes_popup_menu_button_stories.PopupMenuButtonDemoComponent,
  _widgetbook_workspace_aura_ui_auravibes_pressable_stories.PressableDemoComponent,
  _widgetbook_workspace_aura_ui_auravibes_radio_stories.SingleRadioDemoComponent,
  _widgetbook_workspace_aura_ui_auravibes_radio_group_stories.RadioGroupDemoComponent,
  _widgetbook_workspace_aura_ui_auravibes_radio_list_tile_stories.RadioListTileDemoComponent,
  _widgetbook_workspace_aura_ui_auravibes_screen_stories.AuraScreenComponent,
  _widgetbook_workspace_aura_ui_auravibes_selectable_text_stories.SelectableTextDemoComponent,
  _widgetbook_workspace_aura_ui_auravibes_sidebar_stories.SidebarDemoComponent,
  _widgetbook_workspace_aura_ui_auravibes_slider_stories.SliderDemoComponent,
  _widgetbook_workspace_aura_ui_auravibes_snackbar_stories.SnackBarDemoComponent,
  _widgetbook_workspace_aura_ui_auravibes_spinner_stories.AuraSpinnerComponent,
  _widgetbook_workspace_aura_ui_auravibes_switch_stories.SwitchDemoComponent,
  _widgetbook_workspace_aura_ui_auravibes_tabs_basic_stories.AuraTabsComponent,
  _widgetbook_workspace_aura_ui_auravibes_tabs_selector_stories.SelectorTabsDemoComponent,
  _widgetbook_workspace_aura_ui_auravibes_text_stories.AuraTextComponent,
  _widgetbook_workspace_aura_ui_auravibes_tile_stories.AuraTileComponent,
  _widgetbook_workspace_aura_ui_auravibes_tooltip_stories.AuraTooltipComponent,
  _widgetbook_workspace_aura_ui_auravibes_typing_indicator_stories.AuraTypingIndicatorComponent,
];
