name: auravibes_server_client
description: AuraVibes cloud workspace Serverpod client.
version: 0.0.1

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  serverpod_auth_idp_client: 4.0.0-beta.0
  serverpod_client: 4.0.0-beta.0
