name: Flutter Test CI

on:
  push:
    branches:
      - main
      - dev
      - stage
  pull_request:
    branches:
      - main
      - dev
      - stage

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v6

      - name: 🔧 Setup FVM
        uses: kuhnroyal/flutter-fvm-config-action/config@v3
        id: fvm-config-action

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:" # optional, change this to force refresh cache
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
          pub-cache-key: "flutter-pub-:os:-:channel:-:version:-:arch:-${{ hashFiles('pubspec.lock') }}" # optional, change this to force refresh cache of dart pub get dependencies
          # pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
      - name: 🔗 Create FVM symlink for CI
        run: |
          mkdir -p .fvm
          ln -sfn "$FLUTTER_ROOT" .fvm/flutter_sdk

      - uses: bluefireteam/melos-action@main
        with:
          run-bootstrap: true
      - name: 🛠️ Generate Code
        run: melos run generate --no-select

      - name: ✨ Check Formatting
        run: melos run format:check

      - name: 🕵️‍♂️ Analyze
        run: melos analyze

      - name: 🧪 Run Tests
        run: melos run test

      - name: ☁️ SonarCloud Scan
        if: ${{ env.SONAR_TOKEN != '' && (github.event_name != 'pull_request' || !github.event.pull_request.head.repo.fork) }}
        uses: SonarSource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}

      - name: 📦 Dependency Validation
        run: dart run dependency_validator

      - name: 📝 Import Sorting
        run: dart run import_sorter:main --exit-if-changed
