// Mocks generated by Mockito 5.4.6 from annotations
// in auravibes_app/test/providers/tool_calling_manager_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:auravibes_app/domain/entities/conversation.dart' as _i2;
import 'package:auravibes_app/domain/entities/conversation_tool.dart' as _i8;
import 'package:auravibes_app/domain/entities/workspace_tool.dart' as _i9;
import 'package:auravibes_app/domain/enums/message_types.dart' as _i5;
import 'package:auravibes_app/domain/enums/tool_permission_result.dart' as _i10;
import 'package:auravibes_app/domain/repositories/conversation_repository.dart'
    as _i6;
import 'package:auravibes_app/domain/repositories/conversation_tools_repository.dart'
    as _i7;
import 'package:auravibes_app/domain/repositories/message_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMessageEntity_0 extends _i1.SmartFake implements _i2.MessageEntity {
  _FakeMessageEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConversationEntity_1 extends _i1.SmartFake
    implements _i2.ConversationEntity {
  _FakeConversationEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageRepository extends _i1.Mock implements _i3.MessageRepository {
  MockMessageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.MessageEntity>> getMessagesByConversation(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByConversation, [conversationId]),
            returnValue: _i4.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i4.Future<List<_i2.MessageEntity>>);

  @override
  _i4.Future<List<_i2.MessageEntity>> getMessagesByConversationPaginated(
    String? conversationId,
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByConversationPaginated, [
              conversationId,
              limit,
              offset,
            ]),
            returnValue: _i4.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i4.Future<List<_i2.MessageEntity>>);

  @override
  _i4.Future<List<_i2.MessageEntity>> getMessagesByType(
    String? conversationId,
    _i5.MessageType? messageType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByType, [
              conversationId,
              messageType,
            ]),
            returnValue: _i4.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i4.Future<List<_i2.MessageEntity>>);

  @override
  _i4.Future<List<_i2.MessageEntity>> getUserMessages(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserMessages, [conversationId]),
            returnValue: _i4.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i4.Future<List<_i2.MessageEntity>>);

  @override
  _i4.Future<List<_i2.MessageEntity>> getSystemMessages(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSystemMessages, [conversationId]),
            returnValue: _i4.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i4.Future<List<_i2.MessageEntity>>);

  @override
  _i4.Future<_i2.MessageEntity?> getMessageById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageById, [id]),
            returnValue: _i4.Future<_i2.MessageEntity?>.value(),
          )
          as _i4.Future<_i2.MessageEntity?>);

  @override
  _i4.Future<_i2.MessageEntity> createMessage(_i2.MessageToCreate? message) =>
      (super.noSuchMethod(
            Invocation.method(#createMessage, [message]),
            returnValue: _i4.Future<_i2.MessageEntity>.value(
              _FakeMessageEntity_0(
                this,
                Invocation.method(#createMessage, [message]),
              ),
            ),
          )
          as _i4.Future<_i2.MessageEntity>);

  @override
  _i4.Future<_i2.MessageEntity> updateMessage(
    String? id,
    _i2.MessageToUpdate? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMessage, [id, message]),
            returnValue: _i4.Future<_i2.MessageEntity>.value(
              _FakeMessageEntity_0(
                this,
                Invocation.method(#updateMessage, [id, message]),
              ),
            ),
          )
          as _i4.Future<_i2.MessageEntity>);

  @override
  _i4.Future<_i2.MessageEntity?> appendToMessage(String? id, String? delta) =>
      (super.noSuchMethod(
            Invocation.method(#appendToMessage, [id, delta]),
            returnValue: _i4.Future<_i2.MessageEntity?>.value(),
          )
          as _i4.Future<_i2.MessageEntity?>);

  @override
  _i4.Future<bool> deleteMessage(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> messageExists(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#messageExists, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<_i2.MessageEntity>> getMessagesByStatus(
    String? conversationId,
    _i5.MessageStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByStatus, [conversationId, status]),
            returnValue: _i4.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i4.Future<List<_i2.MessageEntity>>);

  @override
  _i4.Future<int> getMessageCountByConversation(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageCountByConversation, [conversationId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<bool> validateMessage(_i2.MessageToCreate? message) =>
      (super.noSuchMethod(
            Invocation.method(#validateMessage, [message]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [ConversationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationRepository extends _i1.Mock
    implements _i6.ConversationRepository {
  MockConversationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.ConversationEntity>> getConversationsByWorkspace(
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationsByWorkspace, [workspaceId]),
            returnValue: _i4.Future<List<_i2.ConversationEntity>>.value(
              <_i2.ConversationEntity>[],
            ),
          )
          as _i4.Future<List<_i2.ConversationEntity>>);

  @override
  _i4.Future<_i2.ConversationEntity?> getConversationById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationById, [id]),
            returnValue: _i4.Future<_i2.ConversationEntity?>.value(),
          )
          as _i4.Future<_i2.ConversationEntity?>);

  @override
  _i4.Future<List<_i2.ConversationEntity>> getPinnedConversations(
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPinnedConversations, [workspaceId]),
            returnValue: _i4.Future<List<_i2.ConversationEntity>>.value(
              <_i2.ConversationEntity>[],
            ),
          )
          as _i4.Future<List<_i2.ConversationEntity>>);

  @override
  _i4.Future<_i2.ConversationEntity> createConversation(
    _i2.ConversationToCreate? conversation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createConversation, [conversation]),
            returnValue: _i4.Future<_i2.ConversationEntity>.value(
              _FakeConversationEntity_1(
                this,
                Invocation.method(#createConversation, [conversation]),
              ),
            ),
          )
          as _i4.Future<_i2.ConversationEntity>);

  @override
  _i4.Future<_i2.ConversationEntity> updateConversation(
    String? id,
    _i2.ConversationToUpdate? conversation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateConversation, [id, conversation]),
            returnValue: _i4.Future<_i2.ConversationEntity>.value(
              _FakeConversationEntity_1(
                this,
                Invocation.method(#updateConversation, [id, conversation]),
              ),
            ),
          )
          as _i4.Future<_i2.ConversationEntity>);

  @override
  _i4.Future<bool> deleteConversation(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> conversationExists(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#conversationExists, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<_i2.ConversationEntity>> searchConversationsByTitle(
    String? workspaceId,
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchConversationsByTitle, [
              workspaceId,
              query,
            ]),
            returnValue: _i4.Future<List<_i2.ConversationEntity>>.value(
              <_i2.ConversationEntity>[],
            ),
          )
          as _i4.Future<List<_i2.ConversationEntity>>);

  @override
  _i4.Future<int> getConversationCountByWorkspace(String? workspaceId) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationCountByWorkspace, [workspaceId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<bool> validateConversation(
    _i2.ConversationToCreate? conversation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validateConversation, [conversation]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateConversationTimestamp(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#updateConversationTimestamp, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [ConversationToolsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationToolsRepository extends _i1.Mock
    implements _i7.ConversationToolsRepository {
  MockConversationToolsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i8.ConversationToolEntity>> getConversationTools(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationTools, [conversationId]),
            returnValue: _i4.Future<List<_i8.ConversationToolEntity>>.value(
              <_i8.ConversationToolEntity>[],
            ),
          )
          as _i4.Future<List<_i8.ConversationToolEntity>>);

  @override
  _i4.Future<List<_i8.ConversationToolEntity>> getEnabledConversationTools(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEnabledConversationTools, [conversationId]),
            returnValue: _i4.Future<List<_i8.ConversationToolEntity>>.value(
              <_i8.ConversationToolEntity>[],
            ),
          )
          as _i4.Future<List<_i8.ConversationToolEntity>>);

  @override
  _i4.Future<_i8.ConversationToolEntity?> getConversationTool(
    String? conversationId,
    String? toolId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationTool, [conversationId, toolId]),
            returnValue: _i4.Future<_i8.ConversationToolEntity?>.value(),
          )
          as _i4.Future<_i8.ConversationToolEntity?>);

  @override
  _i4.Future<bool> setConversationToolEnabled(
    String? conversationId,
    String? toolId, {
    required bool? isEnabled,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setConversationToolEnabled,
              [conversationId, toolId],
              {#isEnabled: isEnabled},
            ),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> setConversationToolsDisabled(
    String? conversationId,
    List<String>? toolIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setConversationToolsDisabled, [
              conversationId,
              toolIds,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> setConversationToolPermission(
    String? conversationId,
    String? toolId, {
    required _i9.ToolPermissionMode? permissionMode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setConversationToolPermission,
              [conversationId, toolId],
              {#permissionMode: permissionMode},
            ),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> toggleConversationTool(
    String? conversationId,
    String? toolId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleConversationTool, [
              conversationId,
              toolId,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> isConversationToolEnabled(
    String? conversationId,
    String? toolId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isConversationToolEnabled, [
              conversationId,
              toolId,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> removeConversationTool(
    String? conversationId,
    String? toolId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeConversationTool, [
              conversationId,
              toolId,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<int> getConversationToolsCount(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationToolsCount, [conversationId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> getEnabledConversationToolsCount(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getEnabledConversationToolsCount, [
              conversationId,
            ]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> copyConversationTools(
    String? sourceConversationId,
    String? targetConversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#copyConversationTools, [
              sourceConversationId,
              targetConversationId,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> validateConversationToolSetting(
    String? conversationId,
    String? toolId, {
    required bool? isEnabled,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #validateConversationToolSetting,
              [conversationId, toolId],
              {#isEnabled: isEnabled},
            ),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> isToolAvailableForConversation(
    String? conversationId,
    String? workspaceId,
    String? toolId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isToolAvailableForConversation, [
              conversationId,
              workspaceId,
              toolId,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<String>> getAvailableToolsForConversation(
    String? conversationId,
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableToolsForConversation, [
              conversationId,
              workspaceId,
            ]),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<_i10.ToolPermissionResult> checkToolPermission({
    required String? conversationId,
    required String? workspaceId,
    required String? toolId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#checkToolPermission, [], {
              #conversationId: conversationId,
              #workspaceId: workspaceId,
              #toolId: toolId,
            }),
            returnValue: _i4.Future<_i10.ToolPermissionResult>.value(
              _i10.ToolPermissionResult.granted,
            ),
          )
          as _i4.Future<_i10.ToolPermissionResult>);
}
